"use client";

import {
  classNames,
  limits,
  perClass,
  primary,
  primaryRow,
  project,
  result,
  stages,
  structure,
  topConfusions,
  training,
} from "@/content/cifar-world";
import type { CifarKey } from "./states";

/**
 * The measurements, as HTML over the canvas.
 *
 * Every number is generated by tools/gen-cifar-world.py, which builds the repository's own module
 * to measure the shapes, checks the parameter count against the tracked run, and verifies the
 * confusion matrix four ways before writing anything. Nothing is typed here.
 *
 * One thing this readout must keep saying: there is no checkpoint in that repository, so no
 * activation and no per-image prediction appears anywhere on this page.
 */

const cls = (name: string) => perClass.find((c) => c.cls === name)!;

function Rows({ items }: { items: { label: string; value: string; note?: string }[] }) {
  return (
    <dl className="world-readout">
      {items.map((item) => (
        <div className="world-readout-row" key={item.label}>
          <dt>{item.label}</dt>
          <dd>
            <strong>{item.value}</strong>
            {item.note ? <span>{item.note}</span> : null}
          </dd>
        </div>
      ))}
    </dl>
  );
}

export default function Readout({ state }: { state: CifarKey }) {
  switch (state) {
    case "image":
      return (
        <Rows
          items={[
            { label: "Dataset", note: `${project.classes} classes, ${project.imageSize}`, value: project.dataset },
            { label: "This image", note: `test index ${primary.index}, shown at native size`, value: primary.cls },
            { label: "Test set", note: "1,000 per class", value: project.testImages.toLocaleString("en-GB") },
          ]}
        />
      );

    case "pixels":
      return (
        <Rows
          items={[
            { label: "Input", note: "three channels, thirty-two square", value: `${project.inputNumbers.toLocaleString("en-GB")} numbers` },
            { label: "Per pixel", note: "no depth, no metadata, no context", value: "Three bytes" },
            { label: "Not upscaled", note: "this is the resolution the model sees", value: "32 × 32" },
          ]}
        />
      );

    case "augment":
      return (
        <>
          <ol className="world-readout-list">
            {training.augmentation.map((a) => (
              <li data-on="" key={a}>
                <code>{a}</code>
              </li>
            ))}
          </ol>
          <p className="world-note">
            The two geometric transforms are drawn here. Colour jitter is applied in the run but its
            magnitude is not recorded in the tracked configuration, so it is named rather than shown.
          </p>
        </>
      );

    case "field":
      return (
        <Rows
          items={[
            { label: "Kernel", note: "padding 1, so the plate keeps its size", value: "3 × 3" },
            { label: "Each output sees", note: "and nothing else, at this depth", value: "9 pixels" },
            { label: "Assumption", note: "nearby pixels belong together", value: "Locality" },
          ]}
        />
      );

    case "features":
      return (
        <>
          <Rows
            items={[
              { label: "Conv block 1", note: `${stages[1].params.toLocaleString("en-GB")} parameters`, value: stages[1].shape.join(" × ") },
              { label: "Channels", note: "a sample of them is drawn", value: `${stages[1].shape[0]}` },
              { label: "Pooling", note: "32 becomes 16", value: "MaxPool 2 × 2" },
            ]}
          />
          <p className="world-note">
            The shapes are measured from the repository&rsquo;s own module. The values inside these
            planes are not: no checkpoint is versioned, so there is no recorded activation to draw.
          </p>
        </>
      );

    case "compress":
      return (
        <ol className="world-readout-list">
          {stages.slice(0, 4).map((s) => (
            <li data-on="" key={s.name}>
              <code>{s.name}</code>
              <span>
                {s.shape.join(" × ")}
                {s.params ? ` · ${s.params.toLocaleString("en-GB")} parameters` : ""}
              </span>
            </li>
          ))}
        </ol>
      );

    case "classifier":
      return (
        <Rows
          items={[
            { label: "Flatten", note: "128 × 4 × 4", value: "2,048" },
            { label: "Hidden", note: `dropout 0.5, then ${project.classes} outputs`, value: "256" },
            {
              label: "Classifier parameters",
              note: `of ${project.parameters.toLocaleString("en-GB")} in total`,
              value: stages[4].params.toLocaleString("en-GB"),
            },
          ]}
        />
      );

    case "decision":
      return (
        <>
          <ol className="world-readout-list">
            {primaryRow
              .filter((r) => r.count >= 100)
              .map((r) => (
                <li
                  data-on=""
                  data-tone={r.cls === primary.cls ? "positive" : "uncertain"}
                  key={r.cls}
                >
                  <code>{r.cls}</code>
                  <span>
                    {r.count} of 1,000{r.cls === primary.cls ? " — correct" : ""}
                  </span>
                </li>
              ))}
          </ol>
          <p className="world-note">
            These are not probabilities for the image above. There is no checkpoint to run, so this
            is the confusion matrix&rsquo;s own row: every one of the 1,000 test cats, and the class
            it was actually assigned.
          </p>
        </>
      );

    case "spread":
      return (
        <>
          <Rows
            items={[
              { label: "Overall", note: `test loss ${result.testLoss}`, value: `${result.testAccuracy}%` },
              { label: "Best class", note: structure.best, value: `${structure.bestAccuracy}%` },
              { label: "Worst class", note: `${structure.worst} — a ${structure.spread}-point spread`, value: `${structure.worstAccuracy}%` },
            ]}
          />
          <p className="world-note">
            The aggregate is the mean of ten very different numbers. On its own it describes almost
            nothing about how this model behaves.
          </p>
        </>
      );

    case "confusion":
      return (
        <>
          <ol className="world-readout-list">
            {topConfusions.slice(0, 3).map((c) => (
              <li data-on="" data-tone="uncertain" key={`${c.from}-${c.to}`}>
                <code>
                  {c.from} → {c.to}
                </code>
                <span>{c.count} of 1,000</span>
              </li>
            ))}
          </ol>
          <p className="world-note">
            {cls("cat").accuracy}% of cats are found. {topConfusions[0].count} of them are called{" "}
            {topConfusions[0].to} — nearly as often as the model gets them right, and the largest
            single cell off the diagonal.
          </p>
        </>
      );

    case "structure":
      return (
        <>
          <Rows
            items={[
              { label: "Vehicles", note: "airplane, automobile, ship, truck", value: `${structure.vehicleAccuracy}%` },
              { label: "Animals", note: "the other six classes", value: `${structure.animalAccuracy}%` },
              {
                label: "Mistakes staying in group",
                note: `${structure.withinGroupErrors.toLocaleString("en-GB")} of ${(structure.withinGroupErrors + structure.acrossGroupErrors).toLocaleString("en-GB")}`,
                value: `${Math.round(structure.withinGroupShare * 100)}%`,
              },
            ]}
          />
          <p className="world-note">
            The boundary the model learned best is not one of the ten it was asked for. It separates
            things with wheels from things with legs, and then struggles inside each side.
          </p>
        </>
      );

    default:
      return (
        <ol className="world-readout-list">
          {limits.slice(0, 4).map((limit) => (
            <li data-on="" data-tone="uncertain" key={limit.label}>
              <code>{limit.label}</code>
              <span>{limit.note}</span>
            </li>
          ))}
        </ol>
      );
  }
}

export { classNames };
