/*
 * GENERATED by tools/gen-hydrology-world.py - do not edit by hand.
 *
 * Uncertainty Quantification in Hydrology, TUM project seminar, Group B.
 * https://github.com/mzquadri/UQ-Hydrology-Seminar-TUM
 * commit 7a5cf09a800fe66853e125160dd429d331237e82
 *
 * Every metric here is transcribed from a machine-readable artifact in that repository and
 * carries the file it came from. The rating curve and both series are evaluated from the
 * coefficients the seminar fitted, so the envelope in the scene is the project's own function.
 */

export const project = {
  repository: "https://github.com/mzquadri/UQ-Hydrology-Seminar-TUM",
  commit: "7a5cf09a800fe66853e125160dd429d331237e82",
  model: "HBV001a",
  modelKind: "Lumped conceptual rainfall-runoff",
  timestep: "Hourly",
  parameters: 18,
  forcing: "Temperature, precipitation, potential evapotranspiration",
  event: "A short, rainfall-dominated high-flow event",
  institution: "Chair of Hydrology and River Basin Management, TUM",
  team: "Group B, three contributors",
} as const;

/** Assignment 1: the calibrated baseline everything else is measured against. */
export const calibration = {
  method: "Differential Evolution",
  strategy: "best1bin",
  generations: 600,
  popsize: 10,
  evaluations: 75480,
  nse: 0.9076,
  ofv: 0.092392,
  referenceNse: 0.907715,
  referenceOfv: 0.092285,
  source: "results/assignment1_finial_gen600_atol-3/final_debug_summary.txt",
} as const;

/** Assignment 1: which processes the event actually needs, established by removing them. */
export const turnoff = [
  { key: "base", label: "Nothing removed", nse: 0.9076 },
  { key: "snow", label: "Snow module off", nse: 0.4959 },
  { key: "lower", label: "Lower reservoir off", nse: -0.7539 },
  { key: "groundwater", label: "Groundwater off", nse: 0.9076 },
] as const;
export const turnoffSource = "results/assignment1_finial_gen600_atol-3/turned_off_processes/NSE_values_tunroff.txt" as const;

/** The stage-discharge rating curve the seminar fitted, and the single power law it rejected. */
export const ratingCurve = {
  form: "Two power laws blended by a sigmoid",
  q1: { a: 1.22871059e-04, h0: 25.033145, b: 2.1538 },
  q2: { a: 5.83762819e-06, h0: 315.640655, b: 3.3829 },
  transition: { centre: 450, width: 6.8602 },
  r2: 0.998705,
  rmse: 0.920025,
  singleR2: 0.883143,
  singleRmse: 8.740415,
  source: "results/assignment5/results_fiting_curve.txt",
} as const;

/** Assignment 4: perturb the rain. */
export const inputExperiment = {
  label: "Precipitation",
  series: 2000,
  perturbation: "C ~ N(1.0, 0.083), multiplicative, clipped to [0.75, 1.25]",
  seed: 42,
  ofvMean: 0.092702,
  ofvStd: 0.00178,
  ofvP5: 0.0897,
  ofvP95: 0.095688,
  nseMean: 0.907298,
  betterByChance: 834,
  recalOfvMean: 0.092483,
  recalNseMean: 0.907517,
  recalBetter: 933,
  recalImproved: 1908,
  meanChangePct: 6.62,
  meanLoss: 0.000417,
  source: "results/assignment4_gen600/uncertainty_analysis_summary.txt",
} as const;

/** Assignment 5: leave the rain alone and perturb the ruler instead. */
export const outputExperiment = {
  label: "Water level",
  series: 2000,
  perturbation: "Additive, uniform on [-25, 25] cm, drawn per timestep",
  seed: 42,
  ofvMean: 0.240774,
  ofvStd: 0.010241,
  ofvP5: 0.2231,
  ofvP95: 0.257444,
  nseMean: 0.759226,
  betterByChance: 0,
  recalOfvMean: 0.232215,
  recalNseMean: 0.767785,
  recalBetter: 0,
  recalImproved: 1513,
  compensationPct: 5.76,
  meanChangePct: 15.54,
  meanLoss: 0.148489,
  unperturbedNse: 0.899967,
  source: "results/assignment5/uncertainty_analysis_summary.txt",
} as const;

/** The comparison the seminar exists to make. Computed from the two means above. */
export const verdict = {
  lossRatio: 356.1,
  exponentAtBase: 2.35,
  exponentAtPeak: 8.48,
  bandAtBase: 8.633,
  bandAtPeak: 337.68,
  bandRatio: 39,
  baseStage: 300,
  peakStage: 525,
} as const;

/** Assignments 2 and 3: which parameter matters depends on where you stand. */
export const sensitivity = {
  local: {
    method: "One-at-a-time, each parameter swept -30% to +30% in 120 steps",
    top: "sl0_fcy",
    topLabel: "Field capacity",
  },
  narrow: {
    method: "Sobol indices, Saltelli sampling, narrow range, NSE",
    top: "sl0_fcy",
    topLabel: "Field capacity",
    totalIndex: 0.4961,
    variance: 0.001941,
    sumTotal: 1.3451,
    source: "results/assignment3/Assignment3_narrow_NSE/sobol_summary_corrected.txt",
  },
  full: {
    method: "Sobol indices, Saltelli sampling, full range, NSE",
    top: "lrr_dre",
    topLabel: "Lower reservoir drainage ratio",
    totalIndex: 0.5947,
    variance: 0.462608,
    sumTotal: 1.856,
    interaction: 1.3804,
    source: "results/assignment3/Assignment3_Results_full_range_nse/sobol_summary_corrected.txt",
  },
} as const;

/** The fitted curve across the stage domain, with the band 25 cm either side. */
export const curve = [
  [260, 15.7081, 12.3281, 19.5299],
  [263.2, 16.174, 12.7377, 20.0531],
  [266.4, 16.6472, 13.1545, 20.5837],
  [269.6, 17.1278, 13.5785, 21.1217],
  [272.8, 17.6157, 14.0096, 21.6672],
  [276.1, 18.1109, 14.448, 22.2201],
  [279.3, 18.6135, 14.8937, 22.7805],
  [282.5, 19.1234, 15.3466, 23.3484],
  [285.7, 19.6408, 15.8068, 23.9237],
  [288.9, 20.1655, 16.2743, 24.5066],
  [292.1, 20.6977, 16.749, 25.097],
  [295.3, 21.2373, 17.2311, 25.695],
  [298.5, 21.7844, 17.7206, 26.3005],
  [301.7, 22.3389, 18.2174, 26.9135],
  [304.9, 22.9009, 18.7215, 27.5341],
  [308.2, 23.4703, 19.2331, 28.1624],
  [311.4, 24.0473, 19.752, 28.7982],
  [314.6, 24.6318, 20.2783, 29.4416],
  [317.8, 25.2238, 20.8121, 30.0926],
  [321, 25.8234, 21.3533, 30.7513],
  [324.2, 26.4305, 21.9019, 31.4176],
  [327.4, 27.0451, 22.458, 32.0916],
  [330.6, 27.6674, 23.0216, 32.7732],
  [333.8, 28.2972, 23.5927, 33.4625],
  [337.1, 28.9346, 24.1713, 34.1595],
  [340.3, 29.5797, 24.7573, 34.8642],
  [343.5, 30.2324, 25.351, 35.5766],
  [346.7, 30.8927, 25.9521, 36.2966],
  [349.9, 31.5606, 26.5608, 37.0243],
  [353.1, 32.2362, 27.1771, 37.7596],
  [356.3, 32.9195, 27.801, 38.5026],
  [359.5, 33.6104, 28.4324, 39.253],
  [362.7, 34.3091, 29.0715, 40.0108],
  [365.9, 35.0154, 29.7181, 40.7758],
  [369.2, 35.7294, 30.3724, 41.5476],
  [372.4, 36.451, 31.0344, 42.326],
  [375.6, 37.1804, 31.7039, 43.1104],
  [378.8, 37.9173, 32.3812, 43.9002],
  [382, 38.6619, 33.0661, 44.6946],
  [385.2, 39.4139, 33.7587, 45.4931],
  [388.4, 40.1732, 34.4589, 46.2959],
  [391.6, 40.9397, 35.1669, 47.1047],
  [394.8, 41.713, 35.8825, 47.9255],
  [398.1, 42.4927, 36.6058, 48.7726],
  [401.3, 43.2783, 37.3368, 49.6765],
  [404.5, 44.0691, 38.0754, 50.6973],
  [407.7, 44.8645, 38.8215, 51.9455],
  [410.9, 45.6638, 39.5751, 53.6091],
  [414.1, 46.4676, 40.336, 55.978],
  [417.3, 47.2783, 41.1039, 59.4405],
  [420.5, 48.1031, 41.8786, 64.4143],
  [423.7, 48.959, 42.6597, 71.1958],
  [426.9, 49.8814, 43.4464, 79.7935],
  [430.2, 50.9393, 44.2383, 89.8839],
  [433.4, 52.2571, 45.0345, 100.9527],
  [436.6, 54.0429, 45.8347, 112.5163],
  [439.8, 56.6097, 46.6396, 124.2624],
  [443, 60.3606, 47.4525, 136.0655],
  [446.2, 65.7024, 48.2821, 147.9306],
  [449.4, 72.8821, 49.1483, 159.9285],
  [452.6, 81.8348, 50.0923, 172.1512],
  [455.8, 92.179, 51.1927, 184.6881],
  [459.1, 103.3893, 52.5895, 197.617],
  [462.3, 115.0111, 54.5118, 211.0021],
  [465.5, 126.7744, 57.2951, 224.8954],
  [468.7, 138.5872, 61.3536, 239.3388],
  [471.9, 150.4734, 67.0752, 254.3671],
  [475.1, 162.5113, 74.6503, 270.0094],
  [478.3, 174.7938, 83.9398, 286.2909],
  [481.5, 187.4082, 94.5131, 303.2338],
  [484.7, 200.4294, 105.8437, 320.8589],
  [487.9, 213.9188, 117.5116, 339.1852],
  [491.2, 227.9261, 129.2882, 358.2312],
  [494.4, 242.4915, 141.112, 378.0145],
  [497.6, 257.6484, 153.023, 398.5526],
  [500.8, 273.4249, 165.1053, 419.8627],
  [504, 289.8455, 177.4515, 441.9618],
  [507.2, 306.9321, 190.1468, 464.8671],
  [510.4, 324.7051, 203.2631, 488.5955],
  [513.6, 343.1832, 216.8591, 513.1641],
  [516.8, 362.3849, 230.9822, 538.59],
  [520.1, 382.3276, 245.671, 564.8905],
  [523.3, 403.0288, 260.9577, 592.0826],
  [526.5, 424.5056, 276.8695, 620.1839],
  [529.7, 446.7751, 293.4303, 649.2117],
  [532.9, 469.8544, 310.6616, 679.1834],
  [536.1, 493.7604, 328.5833, 710.1168],
  [539.3, 518.5103, 347.2141, 742.0294],
  [542.5, 544.1211, 366.5722, 774.9391],
  [545.7, 570.6102, 386.6751, 808.8636],
  [548.9, 597.9946, 407.5402, 843.8209],
  [552.2, 626.2919, 429.1845, 879.829],
  [555.4, 655.5194, 451.6252, 916.9061],
  [558.6, 685.6946, 474.8792, 955.0702],
  [561.8, 716.8351, 498.9636, 994.3398],
  [565, 748.9587, 523.8956, 1034.7331],
] as const;
export const curveMax = 1034.7331 as const;

/**
 * The event, as stage and as discharge.
 *
 * [t, stage_cm, discharge, discharge_at_minus_25cm, discharge_at_plus_25cm]
 *
 * The SHAPE is schematic - fast rise, slow recession, one peak - because the course forcing
 * series is not redistributable and no observed series is reproduced here. Everything done TO
 * that shape is real: each stage is pushed through the fitted rating curve above, and the band
 * is that same curve evaluated 25 cm either side. The band widens at the peak because the
 * curve steepens there, not because it was drawn that way.
 */
export const event = [
  [0, 300, 22.038, 17.9477, 26.5809],
  [0.0084, 300.2, 22.0723, 17.9785, 26.6189],
  [0.0168, 300.74, 22.1664, 18.0627, 26.7229],
  [0.0252, 301.6, 22.3159, 18.1968, 26.8881],
  [0.0336, 302.77, 22.5192, 18.3791, 27.1127],
  [0.042, 304.24, 22.7756, 18.6091, 27.3958],
  [0.0504, 305.99, 23.0847, 18.8866, 27.737],
  [0.0588, 308.03, 23.4469, 19.212, 28.1365],
  [0.0672, 310.34, 23.8625, 19.5857, 28.5945],
  [0.0756, 312.94, 24.3323, 20.0085, 29.1119],
  [0.084, 315.81, 24.8573, 20.4815, 29.6896],
  [0.0924, 318.94, 25.4386, 21.0059, 30.3287],
  [0.1008, 322.35, 26.0777, 21.5831, 31.0305],
  [0.1092, 326.02, 26.7762, 22.2146, 31.7968],
  [0.1176, 329.96, 27.5357, 22.9023, 32.629],
  [0.1261, 334.15, 28.3583, 23.6481, 33.5293],
  [0.1345, 338.61, 29.2459, 24.454, 34.4996],
  [0.1429, 343.32, 30.2009, 25.3223, 35.5422],
  [0.1513, 348.29, 31.2256, 26.2555, 36.6595],
  [0.1597, 353.51, 32.3227, 27.2561, 37.8537],
  [0.1681, 358.99, 33.4948, 28.3267, 39.1275],
  [0.1765, 364.72, 34.7448, 29.4704, 40.4829],
  [0.1849, 370.7, 36.0757, 30.69, 41.9214],
  [0.1933, 376.93, 37.4904, 31.9888, 43.4431],
  [0.2017, 383.41, 38.992, 33.37, 45.0456],
  [0.2101, 390.14, 40.5828, 34.8371, 46.728],
  [0.2185, 397.11, 42.2642, 36.3936, 48.5209],
  [0.2269, 404.33, 44.0346, 38.043, 50.6491],
  [0.2353, 411.8, 45.8894, 39.7884, 54.189],
  [0.2437, 419.51, 47.8387, 41.6317, 62.6472],
  [0.2521, 427.46, 50.0379, 43.5718, 81.3077],
  [0.2605, 435.65, 53.4619, 45.6028, 109.1426],
  [0.2689, 444.08, 61.9702, 47.7302, 140.0651],
  [0.2773, 452.76, 82.2254, 50.1327, 172.6463],
  [0.2857, 461.68, 112.8667, 54.1067, 208.5141],
  [0.2941, 470.83, 146.5169, 64.9745, 249.3137],
  [0.3025, 480.22, 182.2388, 90.0975, 296.2701],
  [0.3109, 489.85, 222.1661, 124.4942, 350.3999],
  [0.3193, 499.72, 268.1005, 161.0568, 412.6791],
  [0.3277, 509.82, 321.3496, 200.7911, 484.1231],
  [0.3361, 520.16, 383.0362, 246.1936, 565.823],
  [0.3445, 521.47, 391.3716, 252.344, 576.7835],
  [0.3529, 515.08, 351.7455, 223.1556, 524.5147],
  [0.3613, 508.87, 316.0386, 196.8749, 477.0372],
  [0.3697, 502.84, 283.8534, 172.9671, 433.9075],
  [0.3782, 496.99, 254.8186, 150.8251, 394.7227],
  [0.3866, 491.3, 228.5772, 129.8258, 359.1163],
  [0.395, 485.78, 204.7716, 109.6243, 326.7535],
  [0.4034, 480.42, 183.0248, 90.7631, 297.3273],
  [0.4118, 475.21, 162.9249, 74.9401, 270.5531],
  [0.4202, 470.16, 144.03, 63.7553, 246.1626],
  [0.4286, 465.25, 125.9426, 57.062, 223.8976],
  [0.437, 460.48, 108.5195, 53.3607, 203.5006],
  [0.4454, 455.85, 92.1949, 51.1945, 184.7067],
  [0.4538, 451.35, 78.0646, 49.702, 167.2358],
  [0.4622, 446.98, 67.2548, 48.4855, 150.7952],
  [0.4706, 442.74, 60.0017, 47.386, 135.1056],
  [0.479, 438.62, 55.5601, 46.3457, 119.9737],
  [0.4874, 434.62, 52.8824, 45.3458, 105.4212],
  [0.4958, 430.73, 51.1519, 44.3809, 91.8146],
  [0.5042, 426.96, 49.8857, 43.4499, 79.8344],
  [0.5126, 423.3, 48.8389, 42.5524, 70.1564],
  [0.521, 419.74, 47.8988, 41.688, 63.0347],
  [0.5294, 416.28, 47.0165, 40.8562, 58.1814],
  [0.5378, 412.93, 46.1721, 40.056, 55.0041],
  [0.5462, 409.67, 45.358, 39.2863, 52.9085],
  [0.5546, 406.5, 44.5714, 38.5462, 51.4501],
  [0.563, 403.43, 43.8114, 37.8344, 50.3471],
  [0.5714, 400.44, 43.0775, 37.1497, 49.438],
  [0.5798, 397.55, 42.3692, 36.4912, 48.6362],
  [0.5882, 394.73, 41.686, 35.8576, 47.8967],
  [0.5966, 392, 41.0273, 35.2479, 47.1973],
  [0.605, 389.34, 40.3923, 34.6612, 46.527],
  [0.6134, 386.76, 39.7802, 34.0964, 45.8808],
  [0.6218, 384.26, 39.1903, 33.5527, 45.2562],
  [0.6303, 381.83, 38.6217, 33.0291, 44.6519],
  [0.6387, 379.47, 38.0736, 32.5249, 44.0673],
  [0.6471, 377.17, 37.5453, 32.0392, 43.5019],
  [0.6555, 374.95, 37.0359, 31.5713, 42.9553],
  [0.6639, 372.78, 36.5447, 31.1203, 42.4269],
  [0.6723, 370.68, 36.0711, 30.6858, 41.9164],
  [0.6807, 368.64, 35.6142, 30.2668, 41.4232],
  [0.6891, 366.66, 35.1735, 29.863, 40.9468],
  [0.6975, 364.74, 34.7483, 29.4735, 40.4866],
  [0.7059, 362.87, 34.338, 29.098, 40.0422],
  [0.7143, 361.05, 33.9421, 28.7357, 39.6128],
  [0.7227, 359.29, 33.5599, 28.3862, 39.1981],
  [0.7311, 357.58, 33.191, 28.049, 38.7975],
  [0.7395, 355.92, 32.8348, 27.7236, 38.4105],
  [0.7479, 354.31, 32.4908, 27.4095, 38.0366],
  [0.7563, 352.74, 32.1587, 27.1064, 37.6753],
  [0.7647, 351.22, 31.8379, 26.8137, 37.3262],
  [0.7731, 349.74, 31.5279, 26.531, 36.9887],
  [0.7815, 348.3, 31.2285, 26.2581, 36.6626],
  [0.7899, 346.91, 30.9392, 25.9945, 36.3473],
  [0.7983, 345.56, 30.6596, 25.7399, 36.0425],
  [0.8067, 344.24, 30.3894, 25.4939, 35.7479],
  [0.8151, 342.96, 30.1282, 25.2562, 35.4629],
  [0.8235, 341.72, 29.8757, 25.0265, 35.1874],
  [0.8319, 340.52, 29.6316, 24.8045, 34.9209],
  [0.8403, 339.35, 29.3955, 24.5899, 34.6631],
  [0.8487, 338.21, 29.1672, 24.3825, 34.4137],
  [0.8571, 337.11, 28.9465, 24.182, 34.1725],
  [0.8655, 336.04, 28.7329, 23.9881, 33.939],
  [0.8739, 335, 28.5264, 23.8006, 33.7132],
  [0.8824, 333.99, 28.3265, 23.6193, 33.4946],
  [0.8908, 333.01, 28.1332, 23.4439, 33.2831],
  [0.8992, 332.06, 27.9461, 23.2742, 33.0783],
  [0.9076, 331.13, 27.765, 23.1101, 32.8801],
  [0.916, 330.23, 27.5898, 22.9513, 32.6883],
  [0.9244, 329.36, 27.4202, 22.7976, 32.5025],
  [0.9328, 328.51, 27.256, 22.6489, 32.3227],
  [0.9412, 327.69, 27.0971, 22.505, 32.1485],
  [0.9496, 326.89, 26.9432, 22.3658, 31.9799],
  [0.958, 326.12, 26.7942, 22.231, 31.8166],
  [0.9664, 325.36, 26.65, 22.1004, 31.6584],
  [0.9748, 324.63, 26.5103, 21.9741, 31.5052],
  [0.9832, 323.92, 26.375, 21.8518, 31.3568],
  [0.9916, 323.23, 26.244, 21.7333, 31.213],
  [1, 322.56, 26.1171, 21.6186, 31.0737],
] as const;

export const limits = [
  { label: "Group coursework", note: "Three contributors across five assignments; individual ownership of any single result is not claimed." },
  { label: "Course inputs are not redistributable", note: "The forcing series, catchment area and the hmg package holding HBV001A are course-provided. The scientific runs cannot be reproduced from the public repository alone." },
  { label: "The event shape here is schematic", note: "No observed hydrograph is reproduced. The rating curve, the perturbation and every metric are the repository's own; the trajectory they act on is a placeholder." },
  { label: "The README and the code disagree", note: "The README describes a plus/minus 15 cm water-level perturbation. The module bounds and the results file both record plus/minus 25 cm; 15 survives only as a stale default argument. The figures here follow the code." },
  { label: "Random error only", note: "The precipitation study perturbs without systematic bias, which its own summary notes is the more consequential case and was not tested." },
  { label: "One event, one catchment", note: "A single short high-flow event. Nothing here establishes that the same ordering holds for longer records or other catchments." },
] as const;

/**
 * The fitted stage-discharge relationship, evaluated.
 *
 * Two power laws blended by a sigmoid, exactly as `ratingCurve` reports them. Kept here rather
 * than in a renderer so the homepage chapter and the detail route's amplification figure evaluate
 * the same function: a curve typed twice is a curve that can disagree with itself.
 *
 * Evaluated either side of the stages the seminar reports, it reproduces the published band
 * widths - 8.633 at base stage and 337.68 at the peak - which is the check that the parameters
 * here and the numbers in `verdict` describe the same fit.
 */
export function ratingDischarge(stage: number): number {
  const w = 1 / (1 + Math.exp(-(stage - ratingCurve.transition.centre) / ratingCurve.transition.width));
  const low =
    stage > ratingCurve.q1.h0 ? ratingCurve.q1.a * Math.pow(stage - ratingCurve.q1.h0, ratingCurve.q1.b) : 0;
  const high =
    stage > ratingCurve.q2.h0 ? ratingCurve.q2.a * Math.pow(stage - ratingCurve.q2.h0, ratingCurve.q2.b) : 0;
  return low * (1 - w) + high * w;
}

/** The measurement uncertainty the seminar actually perturbed the gauge by, in centimetres. */
export const gaugeUncertaintyCm = 25 as const;

/**
 * The discharge interval that a fixed gauge uncertainty produces at a given stage.
 *
 * The input never changes: plus or minus 25 cm, everywhere on the curve. What changes is what the
 * curve does with it.
 */
export function dischargeBand(stage: number) {
  const low = ratingDischarge(stage - gaugeUncertaintyCm);
  const high = ratingDischarge(stage + gaugeUncertaintyCm);
  return { low, high, width: high - low, centre: ratingDischarge(stage) };
}

/** Three positions a reader can be dropped at, for a phone and for a reader who declined motion. */
export const amplificationStops = [
  { key: "low", label: "Low flow", stage: 260 },
  { key: "base", label: "Base stage", stage: verdict.baseStage },
  { key: "peak", label: "Peak stage", stage: verdict.peakStage },
] as const;
