/**
 * InsureAssist, as its own evidence artefacts report it.
 *
 * Generated by `tools/gen-insureassist-world.py` from three files in the repository:
 * `eval/reference_run.json` (the frozen held-out run), `eval/retrieval_config.json` (the
 * configuration frozen before that run was executed), and `data/corpus/manifest.json`.
 *
 * The repository is unusually strict about this and the strictness is the point. Its
 * configuration was frozen on the dev split before the test split was touched, the test split was
 * run once, and `eval/verify_artifacts.py` fails CI if the project's own documentation drifts from
 * the reference run. Retyping any of these numbers here would put the one unchecked copy of them
 * on the public site.
 *
 * Two things are separated throughout. A `metric` is measured and comes from the artefact. A
 * `geometry` value is a drawing decision and measures nothing.
 */

/** The corpus. Three federal forms, redistributable as works of the US Government. */
export const corpus = {
  documents: 3,
  chunks: 314,
  words: 35639,
  characters: 212608,
  hash: "81650e214d2a",
  issuedOn: "2026-06-22",
  retrievedOn: "2026-08-22",
} as const;

/*
 * The three forms.
 *
 * They share a skeleton and a great deal of word-for-word wording, and differ in substance. That
 * is the entire reason this project has a hard problem: a retriever matching on topic can find the
 * right provision in the wrong form.
 */
export const forms = [
  { id: "nfip-sfip-dwelling", form: "Dwelling Form", title: "Standard Flood Insurance Policy - Dwelling Form", citation: "44 CFR Part 61, Appendix A(1) to Part 61", words: 12603, characters: 74960, sha256: "c88e41a8bcdc" },
  { id: "nfip-sfip-general-property", form: "General Property Form", title: "Standard Flood Insurance Policy - General Property Form", citation: "44 CFR Part 61, Appendix A(2) to Part 61", words: 11262, characters: 67255, sha256: "7b33a80ef173" },
  { id: "nfip-sfip-rcbap", form: "RCBAP", title: "Standard Flood Insurance Policy - Residential Condominium Building Association Policy", citation: "44 CFR Part 61, Appendix A(3) to Part 61", words: 11774, characters: 70393, sha256: "229d7bcc62bd" },
] as const;

/** Redistribution basis, verified in the repository's NOTICE. */
export const licence = {
  basis: "17 U.S.C. 105",
  note: "Works of the United States Government are not subject to copyright protection. FEMA authored these forms and promulgated them as federal regulation.",
  publisher: "Federal Emergency Management Agency",
} as const;

/** The frozen configuration. Selected on dev, then not touched again. */
export const config = {
  architecture: "hybrid_rrf",
  denseModel: "BAAI/bge-small-en-v1.5",
  dimension: 384,
  distance: "cosine",
  chunkSize: 800,
  chunkOverlap: 120,
  chunkUnit: "characters",
  bm25K1: 1.5,
  bm25B: 0.75,
  fusion: "reciprocal_rank_fusion",
  fusionK: 60,
  candidateDepth: 20,
  servingTopK: 5,
  frozen: true,
} as const;

/** The question set. Forty labels, hand-authored, split by a deterministic hash. */
export const questions = {
  total: 40,
  answerable: 32,
  unanswerable: 8,
  dev: 18,
  test: 22,
  byCategory: [
    { category: "near_miss", n: 9 },
    { category: "unanswerable", n: 8 },
    { category: "single_chunk", n: 6 },
    { category: "exclusion", n: 5 },
    { category: "time_period", n: 5 },
    { category: "multi_chunk", n: 3 },
    { category: "form_difference", n: 2 },
    { category: "numeric_limit", n: 2 },
  ],
} as const;

/*
 * Held-out results, and the two single-retriever baselines measured on the same corpus, the same
 * labels and the same split. The selected architecture does not win outright and the artefact does
 * not pretend otherwise.
 */
export const results = {
  hitAt1: 0.2778, hitAt3: 0.5, hitAt5: 0.5556,
  recallAt5: 0.463, precisionAt5: 0.1111,
  mrr: 0.42, topDocument: 0.5556,
} as const;

export const retrievers = [
  { key: "dense", label: "Dense only (BGE)", hitAt5: 0.5, mrr: 0.3646, topDocument: 0.5556, selected: false },
  { key: "bm25", label: "BM25 only", hitAt5: 0.6111, mrr: 0.3657, topDocument: 0.3333, selected: false },
  { key: "hybrid", label: "Hybrid RRF", hitAt5: 0.5556, mrr: 0.42, topDocument: 0.5556, selected: true },
] as const;

/*
 * The eighteen answerable held-out questions, exactly as the reference run recorded them.
 *
 * `retrieved` is the real ranked list of chunk IDs the frozen system returned, and every chunk ID
 * carries the form it came from before the hash - which is what makes the wrong-form scene a
 * replay rather than an illustration. Eight of these eighteen put a chunk from the wrong form at
 * rank one.
 */
export const run = [
  { id: "nfip-002", category: "numeric_limit", relevant: ["nfip-sfip-dwelling"], retrievedForms: ["nfip-sfip-dwelling", "nfip-sfip-general-property", "nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-rcbap", "nfip-sfip-dwelling", "nfip-sfip-general-property", "nfip-sfip-dwelling", "nfip-sfip-dwelling", "nfip-sfip-general-property"], topFormCorrect: true, hitAt5: 0.0, reciprocalRank: 0.1667 },
  { id: "nfip-004", category: "single_chunk", relevant: ["nfip-sfip-dwelling"], retrievedForms: ["nfip-sfip-dwelling", "nfip-sfip-dwelling", "nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-dwelling", "nfip-sfip-general-property", "nfip-sfip-dwelling", "nfip-sfip-general-property", "nfip-sfip-rcbap", "nfip-sfip-dwelling"], topFormCorrect: true, hitAt5: 0.0, reciprocalRank: 0.1429 },
  { id: "nfip-005", category: "near_miss", relevant: ["nfip-sfip-general-property"], retrievedForms: ["nfip-sfip-dwelling", "nfip-sfip-general-property", "nfip-sfip-rcbap", "nfip-sfip-rcbap", "nfip-sfip-general-property", "nfip-sfip-dwelling", "nfip-sfip-dwelling", "nfip-sfip-general-property", "nfip-sfip-dwelling", "nfip-sfip-general-property"], topFormCorrect: false, hitAt5: 1.0, reciprocalRank: 0.5 },
  { id: "nfip-008", category: "exclusion", relevant: ["nfip-sfip-dwelling"], retrievedForms: ["nfip-sfip-rcbap", "nfip-sfip-dwelling", "nfip-sfip-general-property", "nfip-sfip-dwelling", "nfip-sfip-general-property", "nfip-sfip-dwelling", "nfip-sfip-dwelling", "nfip-sfip-general-property", "nfip-sfip-dwelling", "nfip-sfip-rcbap"], topFormCorrect: false, hitAt5: 1.0, reciprocalRank: 0.5 },
  { id: "nfip-009", category: "exclusion", relevant: ["nfip-sfip-general-property"], retrievedForms: ["nfip-sfip-rcbap", "nfip-sfip-general-property", "nfip-sfip-general-property", "nfip-sfip-rcbap", "nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-dwelling", "nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-general-property"], topFormCorrect: false, hitAt5: 1.0, reciprocalRank: 0.5 },
  { id: "nfip-014", category: "time_period", relevant: ["nfip-sfip-dwelling"], retrievedForms: ["nfip-sfip-dwelling", "nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-general-property", "nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-dwelling", "nfip-sfip-general-property"], topFormCorrect: true, hitAt5: 1.0, reciprocalRank: 1.0 },
  { id: "nfip-015", category: "time_period", relevant: ["nfip-sfip-dwelling"], retrievedForms: ["nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-general-property", "nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-rcbap", "nfip-sfip-general-property", "nfip-sfip-dwelling"], topFormCorrect: true, hitAt5: 1.0, reciprocalRank: 1.0 },
  { id: "nfip-016", category: "time_period", relevant: ["nfip-sfip-dwelling"], retrievedForms: ["nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-general-property", "nfip-sfip-general-property", "nfip-sfip-rcbap", "nfip-sfip-rcbap", "nfip-sfip-dwelling", "nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-dwelling"], topFormCorrect: true, hitAt5: 1.0, reciprocalRank: 1.0 },
  { id: "nfip-017", category: "time_period", relevant: ["nfip-sfip-general-property"], retrievedForms: ["nfip-sfip-general-property", "nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-general-property", "nfip-sfip-rcbap", "nfip-sfip-dwelling", "nfip-sfip-general-property", "nfip-sfip-general-property", "nfip-sfip-dwelling", "nfip-sfip-general-property"], topFormCorrect: true, hitAt5: 1.0, reciprocalRank: 1.0 },
  { id: "nfip-020", category: "near_miss", relevant: ["nfip-sfip-general-property"], retrievedForms: ["nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-rcbap", "nfip-sfip-rcbap", "nfip-sfip-dwelling", "nfip-sfip-dwelling", "nfip-sfip-dwelling", "nfip-sfip-general-property", "nfip-sfip-rcbap", "nfip-sfip-dwelling"], topFormCorrect: false, hitAt5: 0.0, reciprocalRank: 0.0 },
  { id: "nfip-021", category: "near_miss", relevant: ["nfip-sfip-rcbap"], retrievedForms: ["nfip-sfip-dwelling", "nfip-sfip-dwelling", "nfip-sfip-general-property", "nfip-sfip-rcbap", "nfip-sfip-dwelling", "nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-general-property", "nfip-sfip-general-property", "nfip-sfip-rcbap"], topFormCorrect: false, hitAt5: 0.0, reciprocalRank: 0.0 },
  { id: "nfip-022", category: "numeric_limit", relevant: ["nfip-sfip-dwelling"], retrievedForms: ["nfip-sfip-dwelling", "nfip-sfip-general-property", "nfip-sfip-rcbap", "nfip-sfip-rcbap", "nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-dwelling", "nfip-sfip-dwelling", "nfip-sfip-dwelling", "nfip-sfip-dwelling"], topFormCorrect: true, hitAt5: 0.0, reciprocalRank: 0.0 },
  { id: "nfip-023", category: "single_chunk", relevant: ["nfip-sfip-rcbap"], retrievedForms: ["nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-rcbap", "nfip-sfip-dwelling", "nfip-sfip-dwelling", "nfip-sfip-general-property", "nfip-sfip-general-property", "nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-dwelling"], topFormCorrect: false, hitAt5: 0.0, reciprocalRank: 0.0 },
  { id: "nfip-024", category: "multi_chunk", relevant: ["nfip-sfip-dwelling"], retrievedForms: ["nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-general-property", "nfip-sfip-dwelling", "nfip-sfip-general-property", "nfip-sfip-rcbap", "nfip-sfip-rcbap", "nfip-sfip-rcbap", "nfip-sfip-rcbap", "nfip-sfip-rcbap"], topFormCorrect: true, hitAt5: 1.0, reciprocalRank: 1.0 },
  { id: "nfip-025", category: "multi_chunk", relevant: ["nfip-sfip-general-property"], retrievedForms: ["nfip-sfip-dwelling", "nfip-sfip-general-property", "nfip-sfip-rcbap", "nfip-sfip-rcbap", "nfip-sfip-general-property", "nfip-sfip-dwelling", "nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-dwelling", "nfip-sfip-general-property"], topFormCorrect: false, hitAt5: 1.0, reciprocalRank: 0.5 },
  { id: "nfip-028", category: "near_miss", relevant: ["nfip-sfip-general-property"], retrievedForms: ["nfip-sfip-general-property", "nfip-sfip-rcbap", "nfip-sfip-rcbap", "nfip-sfip-dwelling", "nfip-sfip-dwelling", "nfip-sfip-general-property", "nfip-sfip-rcbap", "nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-dwelling"], topFormCorrect: true, hitAt5: 0.0, reciprocalRank: 0.0 },
  { id: "nfip-031", category: "exclusion", relevant: ["nfip-sfip-general-property"], retrievedForms: ["nfip-sfip-rcbap", "nfip-sfip-general-property", "nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-general-property", "nfip-sfip-dwelling", "nfip-sfip-general-property", "nfip-sfip-dwelling", "nfip-sfip-general-property", "nfip-sfip-dwelling"], topFormCorrect: false, hitAt5: 0.0, reciprocalRank: 0.0 },
  { id: "nfip-032", category: "near_miss", relevant: ["nfip-sfip-rcbap"], retrievedForms: ["nfip-sfip-rcbap", "nfip-sfip-dwelling", "nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-rcbap", "nfip-sfip-rcbap", "nfip-sfip-rcbap", "nfip-sfip-dwelling", "nfip-sfip-rcbap", "nfip-sfip-dwelling"], topFormCorrect: true, hitAt5: 1.0, reciprocalRank: 0.25 },
] as const;

/** How the two retrievers behaved on dev, and why both were kept. */
export const complementarity = {
  rationale: "Dense and BM25 are genuinely complementary on dev: of 14 answerable questions each retriever finds 3 that the other misses (union ceiling 0.857 vs 0.643 for either alone). Reciprocal rank fusion recovers most of that union at 0.786 while also lifting top-document accuracy from 0.357 (dense) to 0.571. Neither retriever alone is defensible when the other holds a fifth of the answers.",
  devHitAt5: 1.0,
  devTopDocument: 0.5714,
  devAnswerable: 14,
} as const;

/** Generation, and what is and is not measured about it. */
export const generation = {
  model: "llama3.2:3b",
  backend: "ollama",
  fineTuned: false,
  citationPrecision: 0.1111,
  citationRecall: 0.463,
  unsupportedCitationRate: 0.0,
  citationsChecked: 90,
  answerableAcceptance: 1.0,
  unanswerableRejection: 0.0,
  falseAnswers: 4,
  judgePublished: false,
} as const;

/*
 * Things the repository decided not to build, each with the reason it gives. Absence is a design
 * decision here, not an omission, and the reasons are the most interesting part of the project.
 */
export const notImplemented = [
  { label: "No reranker", reason: "No cross-encoder or LLM reranker. Dev evidence shows the failure is candidate selection (the right chunk is often absent from the candidate list), not ordering within a good list. A reranker cannot promote what was never retrieved." },
  { label: "No query expansion", reason: "None. It would blur the form distinction the benchmark turns on." },
  { label: "No metadata form filter", reason: "Not implemented. Inferring the target form from query wording is feasible, but hybrid fusion already lifts top-document accuracy to parity with BM25, and a filter that guesses wrong removes the correct document entirely." },
] as const;

/** Verified limitations, taken from the repository's own list. */
export const limits = [
  { label: "Twenty-two held-out questions", note: "Category cells of two to five carry no reliable signal, and per-form numbers are not reported as findings." },
  { label: "Dev did not generalise", note: "Hit@5 was 1.0 on dev and 0.5556 on test - the honest cost of selecting on 14 answerable questions." },
  { label: "It never abstains", note: "Unanswerable rejection rate is 0.0. Every unanswerable question is answered anyway, and no threshold is defensible on this data." },
  { label: "One jurisdiction, one peril", note: "Three US flood policy forms. The result describes this wording, not insurance documents generally." },
] as const;

/** Provenance, so the page can say where every number came from. */
export const provenance = {
  benchmark: "nfip-sfip-retrieval",
  split: "test",
  configHash: "11fa4cbd246d",
  python: "3.13.5",
} as const;


/**
 * How the frozen chunking was chosen, and what that choice cost.
 *
 * Ten configurations swept on the fourteen answerable development questions. The selected row -
 * 800 characters with 120 of overlap - is the one that put a relevant chunk in the top five for
 * every single dev question. On the eighteen held-out questions the same configuration retrieves
 * one in 0.5556 of cases.
 *
 * That gap is the most useful thing in this table. A perfect score on fourteen questions is what
 * selecting on fourteen questions produces, and the held-out number is the one that means
 * anything. The sweep is published here rather than summarised so a reader can see how close the
 * neighbouring configurations were.
 */
export const chunkingSweep = [
  { size: 400, overlap: 80, depth: 10, chunks: 664, hit5: 0.4286, mrr: 0.3824 },
  { size: 400, overlap: 80, depth: 20, chunks: 664, hit5: 0.5, mrr: 0.4167 },
  { size: 600, overlap: 100, depth: 10, chunks: 426, hit5: 0.6429, mrr: 0.4923 },
  { size: 600, overlap: 100, depth: 20, chunks: 426, hit5: 0.7857, mrr: 0.5126 },
  { size: 600, overlap: 150, depth: 10, chunks: 474, hit5: 0.7143, mrr: 0.5185 },
  { size: 600, overlap: 150, depth: 20, chunks: 474, hit5: 0.6429, mrr: 0.5211 },
  { size: 800, overlap: 120, depth: 10, chunks: 314, hit5: 1.0, mrr: 0.6214, selected: true },
  { size: 800, overlap: 120, depth: 20, chunks: 314, hit5: 0.9286, mrr: 0.6071 },
  { size: 1000, overlap: 150, depth: 10, chunks: 251, hit5: 0.7143, mrr: 0.6015 },
  { size: 1000, overlap: 150, depth: 20, chunks: 251, hit5: 0.7143, mrr: 0.6066 },
] as const;
export const chunkingSweepSource = "eval/dev_chunking_sweep.json" as const;

/** The number the sweep produced, beside the number the held-out set produced. */
export const selectionGap = {
  devQuestions: 14,
  devHitAt5: 1.0,
  testQuestions: 18,
  testHitAt5: 0.5556,
  note: "Selected on development questions, reported on held-out ones. The first number is what selection produces; the second is the one that means anything.",
} as const;
