/**
 * The medico training script, as data.
 *
 * Generated by `tools/gen-medico-world.py` from `train_phase4_optimized.py` in mzquadri/medico -
 * the entire repository is that one script plus a README, and it is the only evidence there is.
 *
 * What this project does not have is as important as what it does. There are no trained weights in
 * the repository, no patient data, no held-out metrics and no clinical validation, and its own
 * README states the implementation "must not be used for diagnosis, triage, treatment decisions,
 * or any other clinical purpose". So nothing here is a result. Every number below is a setting, a
 * shape, or a count of things in the code, and the world built from it shows machinery rather than
 * performance. Inventing an AUC to make the scene feel finished would be the one unforgivable
 * thing to do with a medical model.
 */

/** Facts read out of the script. */
export const config = {
  modelName: "ChestXray-DenseNet121-Phase4-MaskedFineTune-14diseases",
  modelVersion: "3.1.0-finetune-masked",
  imageSize: 224,
  batchSize: 4,
  accumulationSteps: 32,
  effectiveBatch: 128,
  learningRate: "5e-06",
  epochs: 15,
  dropout: 0.25,
  focalAlpha: 0.75,
  focalGamma: 2.0,
  labelSmoothing: 0.02,
  gradientClip: 1.0,
  chexpertNanIsUnknown: true,
} as const;

/** The fourteen NIH findings the head predicts, in the script's own order. */
export const findings = [
  { name: "Atelectasis", display: "Atelectasis", index: 0 },
  { name: "Cardiomegaly", display: "Cardiomegaly", index: 1 },
  { name: "Consolidation", display: "Consolidation", index: 2 },
  { name: "Edema", display: "Edema", index: 3 },
  { name: "Effusion", display: "Pleural Effusion", index: 4 },
  { name: "Emphysema", display: "Emphysema", index: 5 },
  { name: "Fibrosis", display: "Fibrosis", index: 6 },
  { name: "Hernia", display: "Hernia", index: 7 },
  { name: "Infiltration", display: "Infiltration", index: 8 },
  { name: "Mass", display: "Mass", index: 9 },
  { name: "Nodule", display: "Nodule", index: 10 },
  { name: "Pleural_Thickening", display: "Pleural Thickening", index: 11 },
  { name: "Pneumonia", display: "Pneumonia", index: 12 },
  { name: "Pneumothorax", display: "Pneumothorax", index: 13 },
] as const;

/*
 * The three sources, and how much of the label space each one can actually speak to.
 *
 * This is the whole engineering story of the project. Combining datasets does not combine their
 * label semantics: CheXpert supplies seven of the fourteen findings and says nothing about the
 * rest, the pneumonia set supplies exactly one, and only NIH covers all fourteen. Treating the
 * silence as a negative would teach the model that every CheXpert chest is free of emphysema,
 * fibrosis, hernia and the rest - so the silence is masked out instead.
 */
export const sources = [
  { key: "chexpert", name: "CheXpert", approxImages: "223K", labelled: 7, labels: ["Atelectasis", "Cardiomegaly", "Consolidation", "Edema", "Effusion", "Pneumonia", "Pneumothorax"], split: "patient-level 80/10/10", note: "Uncertain (-1) and not-mentioned (NaN) are both masked; the seven findings it does not carry are masked wholesale." },
  { key: "nih", name: "NIH ChestX-ray14", approxImages: "112K", labelled: 14, labels: [], split: "patient-level 80/10/10, retried until every finding has 20+ positives in val and test", note: "The only source that speaks to all fourteen channels." },
  { key: "pneumonia", name: "Pneumonia set", approxImages: "5.2K", labelled: 1, labels: ["Pneumonia"], split: "stratified", note: "One channel certain, thirteen masked. A binary corpus does not become a multi-label one by being added to the batch." },
] as const;

/** The four states a single label channel can be in for a single image. */
export const labelStates = [
  { key: "positive", label: "Positive", note: "Counted, and boosted by the positive-only class weight." },
  { key: "negative", label: "Negative", note: "Counted." },
  { key: "uncertain", label: "Uncertain", note: "CheXpert -1. Masked: contributes nothing to loss or metrics." },
  { key: "unsupported", label: "Not supplied", note: "The source does not label this finding at all. Masked." },
] as const;

/** The preprocessing chain, in order, as the script composes it. */
export const preprocessing = [
  { step: "Resize(256)", note: "Smaller edge to 256, aspect preserved" },
  { step: "RandomCrop(224)", note: "CenterCrop at validation - deliberately matched" },
  { step: "CLAHE(2.0, 8x8)", note: "Contrast-limited adaptive histogram equalisation" },
  { step: "RandomHorizontalFlip(0.5)", note: "Training only" },
  { step: "RandomRotation(10)", note: "Training only" },
  { step: "Normalize(0.485, 0.229)", note: "Single-channel ImageNet approximation" },
] as const;

/*
 * DenseNet-121, at the level the script actually configures it. Block depths are the canonical
 * torchvision structure the script loads; it does not define its own layers, so nothing here is a
 * guess about a bespoke architecture.
 */
export const architecture = [
  { name: "conv0", kind: "stem", detail: "7x7 stride 2, 64 channels - RGB weights averaged to one channel" },
  { name: "pool0", kind: "stem", detail: "3x3 max pool, stride 2" },
  { name: "denseblock1", kind: "dense", layers: 6, detail: "6 layers" },
  { name: "transition1", kind: "transition", detail: "1x1 conv, 2x2 average pool" },
  { name: "denseblock2", kind: "dense", layers: 12, detail: "12 layers" },
  { name: "transition2", kind: "transition", detail: "1x1 conv, 2x2 average pool" },
  { name: "denseblock3", kind: "dense", layers: 24, detail: "24 layers" },
  { name: "transition3", kind: "transition", detail: "1x1 conv, 2x2 average pool" },
  { name: "denseblock4", kind: "dense", layers: 16, detail: "16 layers" },
  { name: "pool", kind: "head", detail: "Adaptive average pool to 1024 features" },
  { name: "classifier", kind: "head", detail: "Dropout 0.25 to 512, ReLU, dropout, to 14" },
] as const;

/** The loss, term by term, as the forward pass composes it. */
export const lossTerms = [
  { term: "BCE", detail: "against smoothed targets" },
  { term: "focal", detail: "(1 - p_t)^gamma, hard targets" },
  { term: "alpha", detail: "positives weighted 0.75" },
  { term: "class weight", detail: "positives only" },
  { term: "mask", detail: "zero for uncertain and unsupported" },
] as const;

/*
 * The evaluation machinery that exists, and the results that do not.
 *
 * AUC is computed per finding over only the samples where that channel is certain, and the
 * checkpoint is selected on the *worst* class rather than the mean - excluding Hernia, which the
 * script records as 227 samples, 0.08% of the data. All of that is real code. None of it has
 * published output in the repository.
 */
export const evaluation = {
  metric: "ROC-AUC per finding, mask-aware",
  aggregation: "Mean over findings with enough certain labels",
  selection: "Checkpoint chosen on the minimum class AUC, not the mean",
  excluded: "['Hernia']",
  published: false,
  publishedNote: "Evaluation pipeline implemented; no validated numbers are published in the repository.",
} as const;

/** Stated in the repository README. Shown as a state of the world, not as a footnote. */
export const limits = [
  { label: "No trained weights", note: "Nothing in the repository can make a prediction." },
  { label: "No patient data", note: "Datasets are downloaded from their owners under their own terms." },
  { label: "No held-out metrics", note: "The evaluation code exists; its output is not published." },
  { label: "No clinical validation", note: "Not for diagnosis, triage, or treatment decisions." },
] as const;

