/**
 * The MLOps reference pipeline, as its own evidence says it is.
 *
 * Generated by `tools/gen-mlops-world.py` from two files in mzquadri/MLOps-End-to-End-Pipeline:
 * the EXPECTED block in `scripts/check_reference_run.py`, which its CI asserts against an actual
 * run, and `configs/train_config.yaml`, where the promotion thresholds live so the bar is
 * reviewable in version control.
 *
 * The repository's own argument is that the machinery around a number matters more than the
 * number, and its README says so plainly: this is TF-IDF and logistic regression on short
 * sentences, well above a coin flip and nowhere near a fine-tuned transformer. The world built
 * from this file shows the machinery.
 */

/** What was trained, on what. */
export const experiment = {
  task: "Text classification, sentiment",
  model: "TF-IDF features into logistic regression",
  dataset: "uci-sentiment-labelled-sentences",
  datasetKind: "licensed-download",
  licence: "CC BY 4.0",
  datasetSha256: "afc26626d710",
  bundleFormat: "1.1",
} as const;

/** One seed derives both splits, so the partition is reproducible from the config alone. */
export const split = {
  train: 1800, validation: 600, test: 600,
  randomState: 42, stratified: true,
} as const;

/** Held-out test metrics. CI asserts these against a real run within a tolerance. */
export const results = {
  accuracy: 0.8067,
  f1Weighted: 0.8067,
  rocAuc: 0.8795,
  prAuc: 0.8895,
  baselineAccuracy: 0.5,
  accuracyOverBaseline: 0.3067,
  tolerance: 0.02,
} as const;

/*
 * The promotion gate, exactly as the code composes it: four checks, and `all()` over them.
 *
 * The third is the one the repository says carries the real meaning. An accuracy floor alone is
 * uninformative without the class balance, so the gate also requires a margin over the
 * majority-class baseline measured on the same rows - which keeps it honest if the data ever
 * becomes imbalanced.
 *
 * Thresholds come from the validation split, never from the test split the gate is applied to.
 */
export const gate = [
  { key: "accuracy", label: "Accuracy", value: 0.8067, threshold: 0.75, comparison: ">=", note: "A floor, and on its own not worth much." },
  { key: "f1_weighted", label: "Weighted F1", value: 0.8067, threshold: 0.75, comparison: ">=", note: "Balances the two classes rather than trusting accuracy alone." },
  { key: "accuracy_over_baseline", label: "Margin over baseline", value: 0.3067, threshold: 0.2, comparison: ">=", note: "The check that carries the meaning: how much better than always guessing the majority class." },
  { key: "latency_p95", label: "Latency p95", value: 0.067, threshold: 100, comparison: "<=", note: "In-process, single row. A regression guard, not a service level objective." },
] as const;

/** Input-data checks that run before any of that, and can stop the run outright. */
export const dataChecks = [
  { label: "Nulls", threshold: 0.05, note: "Maximum share of missing values tolerated." },
  { label: "Duplicates", threshold: 0.1, note: "Maximum share of repeated rows tolerated." },
  { label: "Class balance", threshold: 0.1, note: "Minimum share for the smaller class." },
] as const;

/** What a failing data check does. `error` stops the run rather than scoring anyway. */
export const dataFailurePolicy = "error" as const;

/*
 * The registry's stages, and the two rules that make promotion mean something.
 *
 * A candidate cannot be registered straight to production - the code refuses it and says so - and
 * registering to staging at all requires that the bundle has been evaluated and that the gate
 * passed. Production is reachable only by an explicit promotion of something already in staging.
 */
export const stages = [
  { key: "none", label: "Unregistered", note: "A bundle on disk with no claim attached to it." },
  { key: "staging", label: "Staging", note: "Requires an evaluated bundle whose gate passed." },
  { key: "production", label: "Production", note: "Not directly registrable. Reached only by promoting from staging." },
  { key: "archived", label: "Archived", note: "A previous production version, kept rather than overwritten." },
] as const;

/*
 * The six decisions the repository says carry most of the weight. Paraphrased to fit a caption,
 * each one written up at length in its docs/ARCHITECTURE.md with alternatives and failure modes.
 */
export const decisions = [
  { label: "The bundle is the unit of promotion", note: "Model, transformers, metrics, lineage and evaluation move together or not at all, written atomically with a checksum manifest." },
  { label: "Only one function is allowed to fit", note: "A single fitting entry point makes \\u201cno leakage\\u201d a property a test can check rather than a habit." },
  { label: "Validation can refuse", note: "A degenerate dataset stops the run instead of producing a flattering score on it." },
  { label: "The gate requires a margin over a baseline", note: "An accuracy floor alone means nothing without the class balance." },
  { label: "The service starts unready rather than crashing", note: "Liveness and readiness are separate endpoints; readiness answers 503 until a model is genuinely usable." },
  { label: "The reference run uses real, licensed data", note: "Downloaded and checksum-verified on demand, never redistributed." },
] as const;

/** The stack, as the repository actually uses it. Nothing here is aspirational. */
export const stack = [
  { name: "Python 3.11", note: "scikit-learn, TF-IDF, logistic regression" },
  { name: "FastAPI", note: "one service over exactly one production bundle" },
  { name: "Docker", note: "code and config only; a bundle is mounted at run time" },
  { name: "GitHub Actions", note: "runs the suite and the reference-run checker" },
  { name: "MLflow", note: "optional and off by default; the bundle is the source of truth" },
] as const;

/** Verified limitations, taken from the repository's own list. */
export const limits = [
  { label: "A reference implementation", note: "No production traffic has ever hit it." },
  { label: "Six hundred test rows", note: "The interval on accuracy is roughly three points, so a one-point difference between models is noise." },
  { label: "Metrics are aggregate", note: "The dataset pools three sources; per-source performance is not reported and would likely differ." },
  { label: "Latency is in-process", note: "Measured on one machine as a regression guard, not a service level objective." },
  { label: "Monitoring is a counter", note: "A JSON counter endpoint, not a monitoring system." },
  { label: "The synthetic fixture is not evidence", note: "It exists so tests can run offline; a linear model scores about 1.0 on it, and nothing quoted as a result comes from it." },
] as const;

/** Test counts, as the README states them. */
export const tests = { total: 99, offline: 93, container: 6 } as const;

