"use client";

import {
  configuration,
  generator,
  importances,
  lag1Autocorrelation,
  failure,
  limits,
  models,
  project,
  split,
  topTwoShare,
  trendDiagnosis,
} from "@/content/streamflow-world";
import type { StreamflowKey } from "./states";

/**
 * The measurements, as HTML over the canvas.
 *
 * Every number is generated by tools/gen-streamflow-world.py, which regenerates the series from
 * the repository's own fixed-seed generator, loads the repository's own tracked model, and
 * refuses to emit anything unless the metrics it recomputes match the published JSON. So these
 * are the reference run's numbers, not a re-training's, and nothing is typed here.
 */

const model = (key: string) => models.find((m) => m.key === key)!;

function Rows({ items }: { items: { label: string; value: string; note?: string }[] }) {
  return (
    <dl className="world-readout">
      {items.map((item) => (
        <div className="world-readout-row" key={item.label}>
          <dt>{item.label}</dt>
          <dd>
            <strong>{item.value}</strong>
            {item.note ? <span>{item.note}</span> : null}
          </dd>
        </div>
      ))}
    </dl>
  );
}

export default function Readout({ state }: { state: StreamflowKey }) {
  switch (state) {
    case "table":
      return (
        <ol className="world-readout-list">
          {models.map((m) => (
            <li data-on="" data-tone={m.r2 < 0 ? "uncertain" : "positive"} key={m.key}>
              <code>{m.label}</code>
              <span>
                R² {m.r2} · RMSE {m.rmse} · scored on {m.scoredOn}
              </span>
            </li>
          ))}
        </ol>
      );

    case "series":
      return (
        <Rows
          items={[
            { label: "Record", note: `${project.start} to ${project.end}`, value: `${project.days.toLocaleString("en-GB")} days` },
            { label: "Target", note: project.exogenous, value: "Daily mean streamflow" },
            { label: "Kind", note: `fixed seed ${project.seed}`, value: project.kind },
          ]}
        />
      );

    case "written":
      return (
        <>
          <Rows
            items={[
              {
                label: "Recursion",
                note: "each day is mostly the day before",
                value: `y[t] = ${generator.ar}·y[t−1] + …`,
              },
              {
                label: "Plus",
                note: `seasonal pull ${generator.basePull}, rainfall response, noise σ ${generator.noiseSd}`,
                value: `trend ${generator.trendPerDay}/day`,
              },
              {
                label: "Feedback gain",
                note: `so the trend becomes ${generator.effectiveDrift} a day`,
                value: `1/(1−${generator.ar}) = ${generator.arGain}`,
              },
            ]}
          />
          <p className="world-note">
            The river is a recursion with a published answer key. That matters for what any model
            fitted to it can be said to have learned.
          </p>
        </>
      );

    case "split":
      return (
        <Rows
          items={[
            { label: "Train", note: `up to ${split.splitDate}`, value: `${split.trainDays.toLocaleString("en-GB")} days` },
            { label: "Test", note: "the last two years, never shuffled", value: `${split.testDays} days` },
            { label: "Order", note: "no future information reaches the training set", value: "Chronological" },
          ]}
        />
      );

    case "naive":
      return (
        <>
          <Rows
            items={[
              { label: "Baseline", note: model("naive").note, value: model("naive").label },
              { label: "R²", note: `NSE ${model("naive").nse}`, value: `${model("naive").r2}` },
              { label: "MAE / RMSE", note: "almost equal, which is the clue", value: `${model("naive").mae} / ${model("naive").rmse}` },
            ]}
          />
          <p className="world-note">
            An error whose mean absolute value nearly equals its root mean square is not scatter. It
            is an offset.
          </p>
        </>
      );

    case "drift":
      return (
        <>
          <Rows
            items={[
              { label: "Mean bias", note: "prediction below truth, all year", value: `${trendDiagnosis.naiveBias}` },
              {
                label: "Level shift",
                note: `train mean ${trendDiagnosis.trainMean}, test mean ${trendDiagnosis.testMean}`,
                value: `${trendDiagnosis.levelShift}`,
              },
              {
                label: "Difference",
                note: "the baseline's error is the drift",
                value: `${Math.round(Math.abs(trendDiagnosis.naiveBias - trendDiagnosis.levelShift) * 100) / 100}`,
              },
            ]}
          />
          <p className="world-note">
            A day-of-year mean has no trend term, and the generator injects one that its own
            feedback multiplies almost sevenfold. Most of the gap between this row and the others is
            that, not model quality.
          </p>
        </>
      );

    case "sarimax":
      return (
        <>
          <Rows
            items={[
              { label: "Model", note: model("sarimax").note, value: "SARIMAX" },
              { label: "Scored on", note: "the daily series is resampled away", value: model("sarimax").scoredOn },
              { label: "R²", note: `RMSE ${model("sarimax").rmse} on those means`, value: `${model("sarimax").r2}` },
            ]}
          />
          <p className="world-note">
            This row forecasts every one of those months without seeing any of them. It is the only
            model here doing something a forecaster would recognise.
          </p>
        </>
      );

    case "xgboost":
      return (
        <>
          <Rows
            items={[
              { label: "Model", note: model("xgboost").note, value: "XGBoost" },
              { label: "Scored on", note: "one prediction per day", value: model("xgboost").scoredOn },
              { label: "R²", note: `RMSE ${model("xgboost").rmse}, MAPE ${model("xgboost").mape}%`, value: `${model("xgboost").r2}` },
            ]}
          />
          <p className="world-note">
            The prediction sits on top of the truth. The question is what it was given in order to
            get there.
          </p>
        </>
      );

    case "features":
      return (
        <>
          <ol className="world-readout-list">
            {importances.slice(0, 4).map((f, i) => (
              <li data-on="" data-tone={i < 2 ? "uncertain" : undefined} key={f.feature}>
                <code>{f.feature}</code>
                <span>{f.value}</span>
              </li>
            ))}
          </ol>
          <p className="world-note">
            The two most recent lags carry {Math.round(topTwoShare * 1000) / 10}% of the model, on a
            series whose day-to-day autocorrelation is {lag1Autocorrelation}. Rainfall, the thing
            that actually drives the river, carries {importances.find((f) => f.feature === "precip_lag1")?.value}.
          </p>
        </>
      );

    case "onestep":
      return (
        <>
          <Rows
            items={[
              { label: "Horizon", note: "not a recursive multi-day forecast", value: "One step" },
              { label: "Given", note: `lags ${configuration.lags.slice(0, 4).join(", ")} and more`, value: "Yesterday's measurement" },
              { label: "Features", note: `${configuration.trees} trees, depth ${configuration.maxDepth}`, value: `${configuration.features}` },
            ]}
          />
          <p className="world-note">
            Each point predicts tomorrow having been told today. The repository says this plainly in
            its own scope note; it is the single most important sentence in the project.
          </p>
        </>
      );

    case "peaks":
      return (
        <>
          <Rows
            items={[
              {
                label: "On the highest tenth",
                note: `observed flow above ${failure.peakThreshold}`,
                value: `MAE ${failure.peakMae}`,
              },
              { label: "Everywhere else", note: "less than half as much", value: `MAE ${failure.elsewhereMae}` },
              {
                label: "Signed",
                note: `those days hold ${Math.round(failure.peakShareOfSquaredError * 100)}% of the squared error`,
                value: `${failure.peakBias}`,
              },
            ]}
          />
          <p className="world-note">
            The bias is negative, so the misses are undershoots: the model rounds the sharp days
            down. Its worst single day observed {failure.worstObserved} and came in{" "}
            {Math.abs(failure.worstError)} low.
          </p>
        </>
      );

    case "incomparable":
      return (
        <>
          <ol className="world-readout-list">
            {models.map((m) => (
              <li data-on="" data-tone={m.r2 < 0 ? "uncertain" : "positive"} key={m.key}>
                <code>{m.label}</code>
                <span>{m.scoredOn}</span>
              </li>
            ))}
          </ol>
          <p className="world-note">
            Same table, three different questions: predict tomorrow knowing today, forecast two
            years of months blind, and repeat a seasonal average with no trend term. The ranking is
            real; what it ranks is not one thing.
          </p>
        </>
      );

    default:
      return (
        <ol className="world-readout-list">
          {limits.slice(0, 4).map((limit) => (
            <li data-on="" data-tone="uncertain" key={limit.label}>
              <code>{limit.label}</code>
              <span>{limit.note}</span>
            </li>
          ))}
        </ol>
      );
  }
}
