"""
Build src/content/insureassist-world.ts from the repository's own evidence artefacts.

Everything the world shows is read from `eval/reference_run.json`, `eval/retrieval_config.json`
and `data/corpus/manifest.json` in mzquadri/insureassist-rag-mlops. No metric is transcribed by
hand, which matters here more than usual: the repository ships `eval/verify_artifacts.py`, which
fails CI if its own documentation drifts from the reference run, and a portfolio that quietly
retyped those numbers would be the one place in the chain without that check.

Usage: python tools/gen-insureassist-world.py ia_ref.json ia_cfg.json ia_manifest.json
"""

import io
import json
import sys

ref = json.load(open(sys.argv[1] if len(sys.argv) > 1 else "ia_ref.json", encoding="utf-8"))
cfg = json.load(open(sys.argv[2] if len(sys.argv) > 2 else "ia_cfg.json", encoding="utf-8"))
man = json.load(open(sys.argv[3] if len(sys.argv) > 3 else "ia_manifest.json", encoding="utf-8"))

OUT = "src/content/insureassist-world.ts"
r4 = lambda v: round(float(v), 4)
q = lambda s: json.dumps(str(s))

L = []
w = L.append
w('''/**
 * InsureAssist, as its own evidence artefacts report it.
 *
 * Generated by `tools/gen-insureassist-world.py` from three files in the repository:
 * `eval/reference_run.json` (the frozen held-out run), `eval/retrieval_config.json` (the
 * configuration frozen before that run was executed), and `data/corpus/manifest.json`.
 *
 * The repository is unusually strict about this and the strictness is the point. Its
 * configuration was frozen on the dev split before the test split was touched, the test split was
 * run once, and `eval/verify_artifacts.py` fails CI if the project's own documentation drifts from
 * the reference run. Retyping any of these numbers here would put the one unchecked copy of them
 * on the public site.
 *
 * Two things are separated throughout. A `metric` is measured and comes from the artefact. A
 * `geometry` value is a drawing decision and measures nothing.
 */

/** The corpus. Three federal forms, redistributable as works of the US Government. */
export const corpus = {''')
c = ref["corpus"]
w(f'  documents: {c["documents"]},')
w(f'  chunks: {c["chunks"]},')
w(f'  words: {c["words"]},')
w(f'  characters: {c["characters"]},')
w(f'  hash: {q(c["corpus_hash"][:12])},')
w(f'  issuedOn: {q(man["ecfr_issue_date"])},')
w(f'  retrievedOn: {q(man["retrieved_at"])},')
w("} as const;\n")

w('''/*
 * The three forms.
 *
 * They share a skeleton and a great deal of word-for-word wording, and differ in substance. That
 * is the entire reason this project has a hard problem: a retriever matching on topic can find the
 * right provision in the wrong form.
 */''')
w("export const forms = [")
for d in man["documents"]:
    w(f'  {{ id: {q(d["document_id"])}, form: {q(d["form"])}, title: {q(d["title"])},'
      f' citation: {q(d["cfr_citation"])}, words: {d["words"]}, characters: {d["characters"]},'
      f' sha256: {q(d["sha256"][:12])} }},')
w("] as const;\n")

w("/** Redistribution basis, verified in the repository's NOTICE. */")
w("export const licence = {")
w(f'  basis: {q("17 U.S.C. 105")},')
w(f'  note: {q("Works of the United States Government are not subject to copyright protection. FEMA authored these forms and promulgated them as federal regulation.")},')
w(f'  publisher: {q("Federal Emergency Management Agency")},')
w("} as const;\n")

w("/** The frozen configuration. Selected on dev, then not touched again. */")
w("export const config = {")
w(f'  architecture: {q(cfg["architecture"])},')
w(f'  denseModel: {q(cfg["dense"]["model"])},')
w(f'  dimension: {cfg["dense"]["dimension"]},')
w(f'  distance: {q(cfg["dense"]["distance"])},')
w(f'  chunkSize: {cfg["chunking"]["size"]},')
w(f'  chunkOverlap: {cfg["chunking"]["overlap"]},')
w(f'  chunkUnit: {q(cfg["chunking"]["unit"])},')
w(f'  bm25K1: {cfg["bm25"]["k1"]},')
w(f'  bm25B: {cfg["bm25"]["b"]},')
w(f'  fusion: {q(cfg["fusion"]["method"])},')
w(f'  fusionK: {cfg["fusion"]["k"]},')
w(f'  candidateDepth: {cfg["fusion"]["candidate_depth_per_retriever"]},')
w(f'  servingTopK: {cfg["serving_top_k"]},')
w(f'  frozen: {"true" if cfg.get("frozen") else "false"},')
w("} as const;\n")

w("/** The question set. Forty labels, hand-authored, split by a deterministic hash. */")
w("export const questions = {")
qs = ref["questions"]
w(f'  total: {qs["total"]},')
w(f'  answerable: {qs["answerable"]},')
w(f'  unanswerable: {qs["unanswerable"]},')
w(f'  dev: {qs["by_split"]["dev"]},')
w(f'  test: {qs["by_split"]["test"]},')
w("  byCategory: [")
for k, v in sorted(qs["by_category"].items(), key=lambda kv: -kv[1]):
    w(f'    {{ category: {q(k)}, n: {v} }},')
w("  ],")
w("} as const;\n")

w('''/*
 * Held-out results, and the two single-retriever baselines measured on the same corpus, the same
 * labels and the same split. The selected architecture does not win outright and the artefact does
 * not pretend otherwise.
 */''')
m = ref["retrieval"]["metrics"]
w("export const results = {")
w(f'  hitAt1: {r4(m["hit_rate@1"])}, hitAt3: {r4(m["hit_rate@3"])}, hitAt5: {r4(m["hit_rate@5"])},')
w(f'  recallAt5: {r4(m["recall@5"])}, precisionAt5: {r4(m["precision@5"])},')
w(f'  mrr: {r4(m["mrr"])}, topDocument: {r4(m["top_document_accuracy"])},')
w("} as const;\n")

w("export const retrievers = [")
b = ref["retrieval"]["baselines"]
for key, label in [("dense", "Dense only (BGE)"), ("bm25", "BM25 only")]:
    v = b[key]
    w(f'  {{ key: {q(key)}, label: {q(label)}, hitAt5: {r4(v["hit_rate@5"])},'
      f' mrr: {r4(v["mrr"])}, topDocument: {r4(v["top_document_accuracy"])}, selected: false }},')
w(f'  {{ key: "hybrid", label: "Hybrid RRF", hitAt5: {r4(m["hit_rate@5"])},'
  f' mrr: {r4(m["mrr"])}, topDocument: {r4(m["top_document_accuracy"])}, selected: true }},')
w("] as const;\n")

w('''/*
 * The eighteen answerable held-out questions, exactly as the reference run recorded them.
 *
 * `retrieved` is the real ranked list of chunk IDs the frozen system returned, and every chunk ID
 * carries the form it came from before the hash - which is what makes the wrong-form scene a
 * replay rather than an illustration. Eight of these eighteen put a chunk from the wrong form at
 * rank one.
 */''')
w("export const run = [")
for entry in ref["per_question"]:
    docs = [cid.split("#")[0] for cid in entry["retrieved_chunk_ids"]]
    w(f'  {{ id: {q(entry["question_id"])}, category: {q(entry["category"])},'
      f' relevant: {json.dumps(entry["relevant_document_ids"])},'
      f' retrievedForms: {json.dumps(docs)},'
      f' topFormCorrect: {"true" if entry["top_document_correct"] else "false"},'
      f' hitAt5: {r4(entry["hit_rate@5"])}, reciprocalRank: {r4(entry["reciprocal_rank"])} }},')
w("] as const;\n")

w("/** How the two retrievers behaved on dev, and why both were kept. */")
w("export const complementarity = {")
w(f'  rationale: {q(cfg["rationale"])},')
w(f'  devHitAt5: {r4(cfg["dev_selection"]["hit_rate@5"])},')
w(f'  devTopDocument: {r4(cfg["dev_selection"]["top_document_accuracy"])},')
w(f'  devAnswerable: {cfg["dev_selection"]["answerable_questions"]},')
w("} as const;\n")

gen = ref["generation"]
w("/** Generation, and what is and is not measured about it. */")
w("export const generation = {")
w(f'  model: {q(gen["generator"])},')
w(f'  backend: {q(gen["backend"])},')
w(f'  fineTuned: {"true" if gen.get("fine_tuned") else "false"},')
w(f'  citationPrecision: {r4(gen["citations"]["citation_precision"])},')
w(f'  citationRecall: {r4(gen["citations"]["citation_recall"])},')
w(f'  unsupportedCitationRate: {r4(gen["citations"]["unsupported_citation_rate"])},')
w(f'  citationsChecked: {gen["citations"]["citations_checked"]},')
w(f'  answerableAcceptance: {r4(gen["abstention"]["answerable_acceptance_rate"])},')
w(f'  unanswerableRejection: {r4(gen["abstention"]["unanswerable_rejection_rate"])},')
w(f'  falseAnswers: {gen["abstention"]["false_answers"]},')
w(f'  judgePublished: false,')
w("} as const;\n")

w('''/*
 * Things the repository decided not to build, each with the reason it gives. Absence is a design
 * decision here, not an omission, and the reasons are the most interesting part of the project.
 */''')
w("export const notImplemented = [")
for key, label in [("reranker", "No reranker"), ("query_expansion", "No query expansion"),
                   ("metadata_form_filter", "No metadata form filter")]:
    reason = cfg["not_implemented"][key]
    w(f'  {{ label: {q(label)}, reason: {q(reason)} }},')
w("] as const;\n")

w("/** Verified limitations, taken from the repository's own list. */")
w("export const limits = [")
w(f'  {{ label: "Twenty-two held-out questions", note: "Category cells of two to five carry no reliable signal, and per-form numbers are not reported as findings." }},')
w(f'  {{ label: "Dev did not generalise", note: "Hit@5 was {r4(cfg["dev_selection"]["hit_rate@5"])} on dev and {r4(m["hit_rate@5"])} on test - the honest cost of selecting on {cfg["dev_selection"]["answerable_questions"]} answerable questions." }},')
w(f'  {{ label: "It never abstains", note: "Unanswerable rejection rate is {r4(gen["abstention"]["unanswerable_rejection_rate"])}. Every unanswerable question is answered anyway, and no threshold is defensible on this data." }},')
w(f'  {{ label: "One jurisdiction, one peril", note: "Three US flood policy forms. The result describes this wording, not insurance documents generally." }},')
w("] as const;\n")

w("/** Provenance, so the page can say where every number came from. */")
w("export const provenance = {")
w(f'  benchmark: {q(ref["benchmark"])},')
w(f'  split: {q(ref["split"])},')
w(f'  configHash: {q(ref["reproducibility"]["config_hash"][:12])},')
w(f'  python: {q(ref["reproducibility"]["python"])},')
w("} as const;\n")

io.open(OUT, "w", encoding="utf-8", newline="").write("\n".join(L) + "\n")
print(f"wrote {OUT}: {len(ref['per_question'])} run records, "
      f"{sum(1 for e in ref['per_question'] if not e['top_document_correct'])} wrong-form")
