"""
Build src/content/medico-world.ts by reading the training script itself.

Every constant the medico world shows - the fourteen finding names, the focal parameters, the
image size, the effective batch size, the label spaces of each source - is parsed out of
`train_phase4_optimized.py` rather than typed here. That matters more than usual for this project:
the repository publishes no trained weights and no metrics, so the only thing the site can honestly
show is the machinery, and machinery transcribed by hand drifts from the code it claims to describe.

Usage: python tools/gen-medico-world.py path/to/train_phase4_optimized.py
"""

import ast
import io
import re
import sys

SOURCE = sys.argv[1] if len(sys.argv) > 1 else "medico.py"
OUT = "src/content/medico-world.ts"

src = io.open(SOURCE, encoding="utf-8").read()


def const(name, cast=str):
    """Read a module-level assignment out of the script."""
    m = re.search(rf"^{name}\s*=\s*([^\n#]+)", src, re.M)
    if not m:
        raise SystemExit(f"could not find {name}")
    raw = m.group(1).strip()
    try:
        return cast(ast.literal_eval(raw))
    except Exception:
        return raw.strip('"').strip("'")


def string_list(name):
    m = re.search(rf"^{name}\s*=\s*\[(.*?)\]", src, re.M | re.S)
    if not m:
        raise SystemExit(f"could not find list {name}")
    return re.findall(r'"([^"]+)"', m.group(1))


labels = string_list("SELECTED_LABELS")
assert len(labels) == 14, len(labels)

# Which of the fourteen CheXpert actually supplies. Everything else is masked off wholesale.
chex_map = re.search(r"chexpert_to_nih = \{(.*?)\}", src, re.S).group(1)
chexpert_labels = sorted(set(re.findall(r":\s*'([^']+)'", chex_map)))

img = const("IMG_SIZE", int)
batch = const("BATCH_SIZE", int)
accum = const("ACCUMULATION_STEPS", int)

L = []
w = L.append
w('''/**
 * The medico training script, as data.
 *
 * Generated by `tools/gen-medico-world.py` from `train_phase4_optimized.py` in mzquadri/medico -
 * the entire repository is that one script plus a README, and it is the only evidence there is.
 *
 * What this project does not have is as important as what it does. There are no trained weights in
 * the repository, no patient data, no held-out metrics and no clinical validation, and its own
 * README states the implementation "must not be used for diagnosis, triage, treatment decisions,
 * or any other clinical purpose". So nothing here is a result. Every number below is a setting, a
 * shape, or a count of things in the code, and the world built from it shows machinery rather than
 * performance. Inventing an AUC to make the scene feel finished would be the one unforgivable
 * thing to do with a medical model.
 */

/** Facts read out of the script. */''')

w("export const config = {")
w(f'  modelName: "{const("MODEL_NAME")}",')
w(f'  modelVersion: "{const("MODEL_VERSION")}",')
w(f"  imageSize: {img},")
w(f"  batchSize: {batch},")
w(f"  accumulationSteps: {accum},")
w(f"  effectiveBatch: {batch * accum},")
w(f'  learningRate: "{const("LEARNING_RATE")}",')
w(f"  epochs: {const('FINETUNE_EPOCHS', int)},")
w(f"  dropout: {const('DROPOUT', float)},")
w(f"  focalAlpha: {const('FOCAL_ALPHA', float)},")
w(f"  focalGamma: {const('FOCAL_GAMMA', float)},")
w(f"  labelSmoothing: {const('FOCAL_SMOOTHING', float)},")
w(f"  gradientClip: {const('GRADIENT_CLIP_NORM', float)},")
w(f"  chexpertNanIsUnknown: {'true' if const('CHEXPERT_NAN_IS_UNKNOWN') in (True, 'True') else 'false'},")
w("} as const;\n")

w("/** The fourteen NIH findings the head predicts, in the script's own order. */")
w("export const findings = [")
for i, name in enumerate(labels):
    display = "Pleural Effusion" if name == "Effusion" else name.replace("_", " ")
    w(f'  {{ name: "{name}", display: "{display}", index: {i} }},')
w("] as const;\n")

w('''/*
 * The three sources, and how much of the label space each one can actually speak to.
 *
 * This is the whole engineering story of the project. Combining datasets does not combine their
 * label semantics: CheXpert supplies seven of the fourteen findings and says nothing about the
 * rest, the pneumonia set supplies exactly one, and only NIH covers all fourteen. Treating the
 * silence as a negative would teach the model that every CheXpert chest is free of emphysema,
 * fibrosis, hernia and the rest - so the silence is masked out instead.
 */''')
w("export const sources = [")
w(f'  {{ key: "chexpert", name: "CheXpert", approxImages: "223K", labelled: {len(chexpert_labels)},'
  f' labels: {chexpert_labels!r}, split: "patient-level 80/10/10",'
  ' note: "Uncertain (-1) and not-mentioned (NaN) are both masked; the seven findings it does not carry are masked wholesale." },'.replace("'", '"'))
w('  { key: "nih", name: "NIH ChestX-ray14", approxImages: "112K", labelled: 14,'
  ' labels: [], split: "patient-level 80/10/10, retried until every finding has 20+ positives in val and test",'
  ' note: "The only source that speaks to all fourteen channels." },')
w('  { key: "pneumonia", name: "Pneumonia set", approxImages: "5.2K", labelled: 1,'
  ' labels: ["Pneumonia"], split: "stratified",'
  ' note: "One channel certain, thirteen masked. A binary corpus does not become a multi-label one by being added to the batch." },')
w("] as const;\n")

w("/** The four states a single label channel can be in for a single image. */")
w("export const labelStates = [")
w('  { key: "positive", label: "Positive", note: "Counted, and boosted by the positive-only class weight." },')
w('  { key: "negative", label: "Negative", note: "Counted." },')
w('  { key: "uncertain", label: "Uncertain", note: "CheXpert -1. Masked: contributes nothing to loss or metrics." },')
w('  { key: "unsupported", label: "Not supplied", note: "The source does not label this finding at all. Masked." },')
w("] as const;\n")

w("/** The preprocessing chain, in order, as the script composes it. */")
w("export const preprocessing = [")
w(f'  {{ step: "Resize(256)", note: "Smaller edge to 256, aspect preserved" }},')
w(f'  {{ step: "RandomCrop({img})", note: "CenterCrop at validation - deliberately matched" }},')
w('  { step: "CLAHE(2.0, 8x8)", note: "Contrast-limited adaptive histogram equalisation" },')
w('  { step: "RandomHorizontalFlip(0.5)", note: "Training only" },')
w('  { step: "RandomRotation(10)", note: "Training only" },')
w('  { step: "Normalize(0.485, 0.229)", note: "Single-channel ImageNet approximation" },')
w("] as const;\n")

w('''/*
 * DenseNet-121, at the level the script actually configures it. Block depths are the canonical
 * torchvision structure the script loads; it does not define its own layers, so nothing here is a
 * guess about a bespoke architecture.
 */''')
w("export const architecture = [")
w('  { name: "conv0", kind: "stem", detail: "7x7 stride 2, 64 channels - RGB weights averaged to one channel" },')
w('  { name: "pool0", kind: "stem", detail: "3x3 max pool, stride 2" },')
w('  { name: "denseblock1", kind: "dense", layers: 6, detail: "6 layers" },')
w('  { name: "transition1", kind: "transition", detail: "1x1 conv, 2x2 average pool" },')
w('  { name: "denseblock2", kind: "dense", layers: 12, detail: "12 layers" },')
w('  { name: "transition2", kind: "transition", detail: "1x1 conv, 2x2 average pool" },')
w('  { name: "denseblock3", kind: "dense", layers: 24, detail: "24 layers" },')
w('  { name: "transition3", kind: "transition", detail: "1x1 conv, 2x2 average pool" },')
w('  { name: "denseblock4", kind: "dense", layers: 16, detail: "16 layers" },')
w('  { name: "pool", kind: "head", detail: "Adaptive average pool to 1024 features" },')
w(f'  {{ name: "classifier", kind: "head", detail: "Dropout {const("DROPOUT", float)} to 512, ReLU, dropout, to 14" }},')
w("] as const;\n")

w("/** The loss, term by term, as the forward pass composes it. */")
w("export const lossTerms = [")
w('  { term: "BCE", detail: "against smoothed targets" },')
w('  { term: "focal", detail: "(1 - p_t)^gamma, hard targets" },')
w('  { term: "alpha", detail: "positives weighted 0.75" },')
w('  { term: "class weight", detail: "positives only" },')
w('  { term: "mask", detail: "zero for uncertain and unsupported" },')
w("] as const;\n")

w('''/*
 * The evaluation machinery that exists, and the results that do not.
 *
 * AUC is computed per finding over only the samples where that channel is certain, and the
 * checkpoint is selected on the *worst* class rather than the mean - excluding Hernia, which the
 * script records as 227 samples, 0.08% of the data. All of that is real code. None of it has
 * published output in the repository.
 */''')
w("export const evaluation = {")
w('  metric: "ROC-AUC per finding, mask-aware",')
w('  aggregation: "Mean over findings with enough certain labels",')
w('  selection: "Checkpoint chosen on the minimum class AUC, not the mean",')
w(f'  excluded: "{const("RARE_DISEASES")}",')
w('  published: false,')
w('  publishedNote: "Evaluation pipeline implemented; no validated numbers are published in the repository.",')
w("} as const;\n")

w("/** Stated in the repository README. Shown as a state of the world, not as a footnote. */")
w("export const limits = [")
w('  { label: "No trained weights", note: "Nothing in the repository can make a prediction." },')
w('  { label: "No patient data", note: "Datasets are downloaded from their owners under their own terms." },')
w('  { label: "No held-out metrics", note: "The evaluation code exists; its output is not published." },')
w('  { label: "No clinical validation", note: "Not for diagnosis, triage, or treatment decisions." },')
w("] as const;\n")

io.open(OUT, "w", encoding="utf-8", newline="").write("\n".join(L) + "\n")
print(f"wrote {OUT}: {len(labels)} findings, {len(chexpert_labels)} CheXpert labels")
