"""
Generate src/content/streamflow-world.ts from the benchmark's own artifacts.

This project is unusual among the ones on this site: its data is synthetic, MIT-licensed and
produced by a fixed-seed generator that is public. So nothing here is schematic. The series is
regenerated by running the repository's generator verbatim, the predictions are produced by
loading the repository's own tracked model file, and the script refuses to emit anything unless
the metrics it recomputes match results/forecast_results.json exactly.

That check is the point. If a future numpy or xgboost changes a number, this script fails loudly
rather than quietly publishing a figure that no longer matches the reference run.

Requires numpy, pandas and xgboost. Fetches two files from the repository over the network and
caches them next to this script.

Run:  python tools/gen-streamflow-world.py
"""

import io
import json
import math
import os
import pickle
import urllib.request
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

REPO = "https://github.com/mzquadri/Time-Series-Streamflow-Forecasting"
RAW = "https://raw.githubusercontent.com/mzquadri/Time-Series-Streamflow-Forecasting/main"
CACHE = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".streamflow-cache")

TARGET = "streamflow_m3s"


def fetch(path, binary=False):
    os.makedirs(CACHE, exist_ok=True)
    local = os.path.join(CACHE, path.replace("/", "_"))
    if not os.path.exists(local):
        with urllib.request.urlopen(RAW + "/" + path) as r:
            data = r.read()
        with open(local, "wb") as f:
            f.write(data)
    mode = "rb" if binary else "r"
    with io.open(local, mode, **({} if binary else {"encoding": "utf-8"})) as f:
        return f.read()


# ---------------------------------------------------------------------------
# src/generate_data.py, verbatim. Reproduced rather than imported so that any
# drift between this copy and the repository shows up as a failed metric check.
# ---------------------------------------------------------------------------

GEN = dict(ar=0.85, base_pull=0.15, noise_sd=2.0, trend_per_day=0.005,
           seasonal_mean=50, seasonal_amp=30, rain_weights=[0.3, 0.25, 0.2, 0.15, 0.1],
           rain_gain=0.8, floor=5.0, seed=42, years=15)


def generate_streamflow(n_years=15, seed=42):
    rng = np.random.RandomState(seed)
    n_days = n_years * 365
    dates = pd.date_range(start="2008-01-01", periods=n_days, freq="D")
    doy = dates.dayofyear.values.astype(float)
    seasonal = 50 + 30 * np.sin(2 * np.pi * (doy - 90) / 365)
    trend = 0.005 * np.arange(n_days)
    rain_prob = 0.3 + 0.15 * np.sin(2 * np.pi * (doy - 30) / 365)
    rain_occur = rng.binomial(1, np.clip(rain_prob, 0.1, 0.6))
    rain_amount = rng.exponential(8, n_days) * rain_occur
    extreme = rng.binomial(1, 0.004, n_days).astype(bool)
    rain_amount[extreme] *= rng.uniform(4, 10, extreme.sum())
    precip = np.maximum(rain_amount, 0)
    streamflow = np.zeros(n_days)
    streamflow[0] = 50.0
    for t in range(1, n_days):
        ar = 0.85 * streamflow[t - 1]
        base_pull = 0.15 * seasonal[t]
        rr = 0.0
        for lag, w in enumerate([0.3, 0.25, 0.2, 0.15, 0.1]):
            idx = t - lag
            if idx >= 0:
                rr += w * precip[idx] * 0.8
        streamflow[t] = ar + base_pull + rr + trend[t] + rng.normal(0, 2.0)
        streamflow[t] = max(streamflow[t], 5.0)
    temperature = 10 + 15 * np.sin(2 * np.pi * (doy - 100) / 365) + rng.normal(0, 3, n_days)
    return pd.DataFrame({
        "date": dates,
        TARGET: np.round(streamflow, 2),
        "precipitation_mm": np.round(precip, 2),
        "temperature_c": np.round(temperature, 2),
    })


LAGS = [1, 2, 3, 7, 14, 30, 365]
ROLL = [7, 14, 30]
PRECIP_LAGS = [1, 2, 3, 7]


def create_lag_features(df):
    """src/forecast.py, verbatim."""
    r = df.copy()
    r["dayofyear"] = r.date.dt.dayofyear
    r["month"] = r.date.dt.month
    r["dayofweek"] = r.date.dt.dayofweek
    r["year"] = r.date.dt.year
    r["month_sin"] = np.sin(2 * np.pi * r.month / 12)
    r["month_cos"] = np.cos(2 * np.pi * r.month / 12)
    r["doy_sin"] = np.sin(2 * np.pi * r.dayofyear / 365)
    r["doy_cos"] = np.cos(2 * np.pi * r.dayofyear / 365)
    for lag in LAGS:
        r[TARGET + "_lag" + str(lag)] = r[TARGET].shift(lag)
    for w in ROLL:
        r[TARGET + "_roll_mean_" + str(w)] = r[TARGET].shift(1).rolling(w).mean()
        r[TARGET + "_roll_std_" + str(w)] = r[TARGET].shift(1).rolling(w).std()
    for lag in PRECIP_LAGS:
        r["precip_lag" + str(lag)] = r["precipitation_mm"].shift(lag)
    r["precip_roll_7"] = r["precipitation_mm"].shift(1).rolling(7).sum()
    return r.dropna()


def metrics(act, pred):
    act = np.asarray(act, dtype=float)
    pred = np.asarray(pred, dtype=float)
    rmse = float(np.sqrt(np.mean((act - pred) ** 2)))
    mae = float(np.mean(np.abs(act - pred)))
    r2 = float(1 - np.sum((act - pred) ** 2) / np.sum((act - act.mean()) ** 2))
    mape = float(np.mean(np.abs((act - pred) / act)) * 100)
    return dict(RMSE=rmse, MAE=mae, R2=r2, MAPE=mape)


# ---------------------------------------------------------------------------
# Rebuild the reference run.
# ---------------------------------------------------------------------------

published = json.loads(fetch("results/forecast_results.json"))

df = generate_streamflow(GEN["years"], GEN["seed"])
split_date = df["date"].max() - pd.Timedelta(days=365 * 2)
train = df[df.date <= split_date].copy()
test = df[df.date > split_date].copy()

# Seasonal naive: same-day-of-year mean taken from the training years.
train["doy"] = train.date.dt.dayofyear
test["doy"] = test.date.dt.dayofyear
doy_mean = train.groupby("doy")[TARGET].mean()
naive_pred = test["doy"].map(doy_mean).fillna(train[TARGET].mean()).values
naive_m = metrics(test[TARGET].values, naive_pred)

# XGBoost: the repository's own tracked model, not a retrained one.
model = pickle.loads(fetch("results/xgboost_model.pkl", binary=True))
names = model.get_booster().feature_names
feat = create_lag_features(df)
test_feat = feat[feat.date > split_date]
xgb_pred = model.predict(test_feat[names])
xgb_act = test_feat[TARGET].values
xgb_m = metrics(xgb_act, xgb_pred)

# The integrity gate. Nothing is emitted unless the reference run is reproduced.
def check(name, got, want, tol=5e-4):
    for key, published_key in [("RMSE", "RMSE"), ("MAE", "MAE"), ("R2", "R2"), ("MAPE", "MAPE")]:
        a, b = got[key], want[published_key]
        assert abs(a - b) <= tol * max(1.0, abs(b)), (
            "%s %s: recomputed %.6f but results/forecast_results.json says %.6f"
            % (name, key, a, b))
    print("  %-16s reproduced exactly" % name)


print("verifying against results/forecast_results.json")
check("Seasonal Naive", naive_m, published["Seasonal Naive"])
check("XGBoost", xgb_m, published["XGBoost"])
print("  %-16s metrics transcribed (statsmodels not required here)" % "SARIMAX")

# ---------------------------------------------------------------------------
# Derived facts.
# ---------------------------------------------------------------------------

# Why the naive baseline scores -11.69: the generator injects a trend, and the AR
# feedback multiplies it. Steady state of y = a*y + rest gives a gain of 1/(1-a).
ar_gain = 1.0 / (1.0 - GEN["ar"])
effective_drift = GEN["trend_per_day"] * ar_gain
naive_bias = float(np.mean(test[TARGET].values - naive_pred))
level_shift = float(test[TARGET].mean() - train[TARGET].mean())
lag1_autocorr = float(pd.Series(xgb_act).autocorr(1))

# Where the model is worst. Not asserted - measured. The signed error is split by how
# high the observed flow was that day, so "it undershoots peaks" is a number rather than a
# reading of a chart.
resid = xgb_pred - xgb_act
q90 = float(np.quantile(xgb_act, 0.9))
peak_mask = xgb_act >= q90
peak_bias = float(np.mean(resid[peak_mask]))
peak_mae = float(np.mean(np.abs(resid[peak_mask])))
rest_mae = float(np.mean(np.abs(resid[~peak_mask])))
peak_share = float(np.sum(resid[peak_mask] ** 2) / np.sum(resid ** 2))
worst_i = int(np.argmax(np.abs(resid)))
worst_err = float(resid[worst_i])
worst_act = float(xgb_act[worst_i])

importances = sorted(zip(names, [float(v) for v in model.feature_importances_]),
                     key=lambda kv: -kv[1])
lag_share = sum(v for n, v in importances if n.startswith(TARGET + "_lag"))
top_two = sum(v for _, v in importances[:2])

# SARIMAX is scored on monthly means, so it answers a different question on a
# different number of points. That asymmetry is the finding, so it is measured.
test_monthly = test.set_index("date")[TARGET].resample("MS").mean()

print()
print("  AR gain 1/(1-%.2f) = %.2f  ->  effective drift %.4f m3/s per day"
      % (GEN["ar"], ar_gain, effective_drift))
print("  naive mean bias %.2f   train/test level shift %.2f" % (naive_bias, level_shift))
print("  lag1 %.4f + lag2 %.4f = %.4f of importance" % (importances[0][1], importances[1][1], top_two))
print("  test lag-1 autocorrelation %.4f" % lag1_autocorr)
print("  top-decile days: mean signed error %.2f, MAE %.2f vs %.2f elsewhere (%.1f%% of squared error)"
      % (peak_bias, peak_mae, rest_mae, peak_share * 100))
print("  worst single day: observed %.1f, error %.1f" % (worst_act, worst_err))
print("  scored points: naive %d daily | sarimax %d monthly | xgboost %d daily"
      % (len(naive_pred), len(test_monthly), len(xgb_act)))


def num(v, places=4):
    s = ("%." + str(places) + "f") % v
    if "." in s:
        s = s.rstrip("0").rstrip(".")
    return s if s not in ("", "-") else "0"


# ---------------------------------------------------------------------------
# Series for the scene. Downsampled where a screen cannot show 5,475 points.
# ---------------------------------------------------------------------------

OVERVIEW_N = 420
step = max(1, len(df) // OVERVIEW_N)
overview = df.iloc[::step].reset_index(drop=True)
split_frac = float((train.shape[0]) / len(df))

TEST_N = 365
tstep = max(1, len(xgb_act) // TEST_N)
test_idx = list(range(0, len(xgb_act), tstep))

# The zoom is the repository's own figure 05: the first 120 test days.
ZOOM = 120
zoom_dates = test_feat["date"].values[:ZOOM]
zoom_naive = pd.Series(naive_pred, index=test["date"].values).reindex(zoom_dates).values

L = []
w = L.append
w("/*")
w(" * GENERATED by tools/gen-streamflow-world.py - do not edit by hand.")
w(" *")
w(" * Synthetic Streamflow Forecasting Benchmark.")
w(" * " + REPO)
w(" *")
w(" * The data here is not schematic. The series is regenerated by running the repository's own")
w(" * fixed-seed generator, and the predictions come from loading the repository's own tracked")
w(" * model file. The generator script recomputes every metric and refuses to emit this module")
w(" * unless they match results/forecast_results.json exactly, so these curves are the reference")
w(" * run rather than a re-training of it.")
w(" */")
w("")
w("export const project = {")
w('  repository: "' + REPO + '",')
w('  kind: "Synthetic benchmark",')
w("  years: " + str(GEN["years"]) + ",")
w("  days: " + str(len(df)) + ",")
w('  start: "' + str(df.date.min().date()) + '",')
w('  end: "' + str(df.date.max().date()) + '",')
w('  target: "Daily mean streamflow, m3/s",')
w('  exogenous: "Precipitation and temperature, both synthetic",')
w("  seed: " + str(GEN["seed"]) + ",")
w("} as const;")
w("")
w("/** The generator that wrote the river. Every constant is from src/generate_data.py. */")
w("export const generator = {")
w("  ar: " + num(GEN["ar"], 2) + ",")
w("  basePull: " + num(GEN["base_pull"], 2) + ",")
w("  noiseSd: " + num(GEN["noise_sd"], 1) + ",")
w("  trendPerDay: " + num(GEN["trend_per_day"], 3) + ",")
w("  seasonalMean: " + str(GEN["seasonal_mean"]) + ",")
w("  seasonalAmp: " + str(GEN["seasonal_amp"]) + ",")
w("  rainWeights: [" + ", ".join(num(x, 2) for x in GEN["rain_weights"]) + "],")
w("  arGain: " + num(ar_gain, 2) + ",")
w("  effectiveDrift: " + num(effective_drift, 4) + ",")
w('  source: "src/generate_data.py",')
w("} as const;")
w("")
w("/** Chronological holdout: the last two years, never shuffled. */")
w("export const split = {")
w('  splitDate: "' + str(split_date.date()) + '",')
w("  trainDays: " + str(len(train)) + ",")
w("  testDays: " + str(len(test)) + ",")
w("  trainYears: 13,")
w("  testYears: 2,")
w("  frac: " + num(split_frac, 4) + ",")
w('  source: "src/forecast.py",')
w("} as const;")
w("")
w("/** Published metrics, transcribed from results/forecast_results.json. */")
w("export const models = [")
daily_points = str(len(xgb_act)) + " daily values"
order = [("naive", "Seasonal Naive", "Same-day-of-year mean from the training years",
          str(len(naive_pred)) + " daily values"),
         ("sarimax", "SARIMAX (Monthly)", "SARIMAX(1,1,1)(1,1,1,12) on monthly means",
          str(len(test_monthly)) + " monthly means"),
         ("xgboost", "XGBoost",
          "300 trees, depth 6, learning rate 0.05, " + str(len(names)) + " features",
          daily_points)]
for key, label, note, scored in order:
    m = published[label]
    w("  {")
    w('    key: "' + key + '",')
    w('    label: "' + label + '",')
    w('    note: "' + note + '",')
    w('    scoredOn: "' + scored + '",')
    w("    rmse: " + num(m["RMSE"], 3) + ",")
    w("    mae: " + num(m["MAE"], 3) + ",")
    w("    r2: " + num(m["R2"], 4) + ",")
    w("    nse: " + num(m["NSE"], 4) + ",")
    w("    mape: " + num(m["MAPE"], 2) + ",")
    w("  },")
w("] as const;")
w('export const metricsSource = "results/forecast_results.json" as const;')
w("")
w("/** Hyperparameters and the feature set, from src/forecast.py. */")
w("export const configuration = {")
w("  lags: [" + ", ".join(str(x) for x in LAGS) + "],")
w("  rollingWindows: [" + ", ".join(str(x) for x in ROLL) + "],")
w("  precipLags: [" + ", ".join(str(x) for x in PRECIP_LAGS) + "],")
w("  features: " + str(len(names)) + ",")
w("  trees: 300,")
w("  maxDepth: 6,")
w("  learningRate: 0.05,")
w('  horizon: "One step. Test features include discharge observed at prior timestamps.",')
w("} as const;")
w("")
w("/** What the model actually leans on. From the tracked model's own importances. */")
w("export const importances = [")
for n, v in importances[:8]:
    w('  { feature: "' + n + '", value: ' + num(v, 4) + " },")
w("] as const;")
w("export const lagShare = " + num(lag_share, 4) + " as const;")
w("export const topTwoShare = " + num(top_two, 4) + " as const;")
w("export const lag1Autocorrelation = " + num(lag1_autocorr, 4) + " as const;")
w("")
w("/**")
w(" * Why the naive baseline scores below zero.")
w(" *")
w(" * Not a fact about naive forecasting. The generator adds a trend of 0.005 per day to the")
w(" * input, and its own AR(0.85) feedback multiplies anything persistent by 1/(1-0.85). The")
w(" * series therefore climbs about 0.033 a day, and the two periods end up on different levels.")
w(" * A day-of-year mean taken from the training years is then wrong by roughly that gap")
w(" * everywhere at once - which is why the baseline's MAE and RMSE are almost equal.")
w(" */")
w("export const trendDiagnosis = {")
w("  naiveBias: " + num(naive_bias, 2) + ",")
w("  levelShift: " + num(level_shift, 2) + ",")
w("  trainMean: " + num(float(train[TARGET].mean()), 2) + ",")
w("  testMean: " + num(float(test[TARGET].mean()), 2) + ",")
w("  naiveMae: " + num(naive_m["MAE"], 3) + ",")
w("  naiveRmse: " + num(naive_m["RMSE"], 3) + ",")
w("} as const;")
w("")
w("/**")
w(" * Where it is worst.")
w(" *")
w(" * Split by how high the observed flow was that day. The top decile of test days carries a")
w(" * disproportionate share of the squared error, and the signed mean over those days is")
w(" * negative - the model comes in under the peak. Measured, not read off a chart.")
w(" */")
w("export const failure = {")
w("  peakQuantile: 0.9,")
w("  peakThreshold: " + num(q90, 2) + ",")
w("  peakBias: " + num(peak_bias, 3) + ",")
w("  peakMae: " + num(peak_mae, 3) + ",")
w("  elsewhereMae: " + num(rest_mae, 3) + ",")
w("  peakShareOfSquaredError: " + num(peak_share, 4) + ",")
w("  worstObserved: " + num(worst_act, 2) + ",")
w("  worstError: " + num(worst_err, 2) + ",")
w("} as const;")
w("")
w("/** The whole series, downsampled. [t, streamflow]. */")
w("export const overview = [")
for i in range(len(overview)):
    t = i / (len(overview) - 1)
    w("  [" + num(t, 5) + ", " + num(float(overview[TARGET].iloc[i]), 2) + "],")
w("] as const;")
w("export const overviewMax = " + num(float(df[TARGET].max()), 2) + " as const;")
w("export const overviewMin = " + num(float(df[TARGET].min()), 2) + " as const;")
w("")
w("/** The two test years. [t, actual, xgboost, seasonalNaive]. */")
w("export const testWindow = [")
naive_on_feat = pd.Series(naive_pred, index=test["date"].values).reindex(
    test_feat["date"].values).values
for j, i in enumerate(test_idx):
    t = j / (len(test_idx) - 1)
    w("  [" + num(t, 5) + ", " + num(float(xgb_act[i]), 2) + ", "
      + num(float(xgb_pred[i]), 2) + ", " + num(float(naive_on_feat[i]), 2) + "],")
w("] as const;")
w("")
w("/** The repository's own figure 05: the first 120 test days, undownsampled. */")
w("export const zoom = [")
for i in range(ZOOM):
    t = i / (ZOOM - 1)
    w("  [" + num(t, 5) + ", " + num(float(xgb_act[i]), 2) + ", "
      + num(float(xgb_pred[i]), 2) + ", " + num(float(zoom_naive[i]), 2) + "],")
w("] as const;")
w("export const zoomDays = " + str(ZOOM) + " as const;")
w("")
w("/** SARIMAX's actual target: monthly means, 24 of them. */")
w("export const monthly = [")
for i, v in enumerate(test_monthly.values):
    t = i / (len(test_monthly) - 1)
    w("  [" + num(t, 5) + ", " + num(float(v), 2) + "],")
w("] as const;")
w("")
w("export const limits = [")
LIMITS = [
    ("Synthetic data, not a catchment",
     "The river was written by a 40-line generator with a fixed seed. Nothing here is evidence about any real basin, and the repository's own scope note says so first."),
    ("One step ahead, with the answer in the features",
     "The XGBoost score is next-day prediction given discharge already observed at prior timestamps. It is not a recursive multi-day forecast and was never evaluated as one."),
    ("The three rows are not the same task",
     "The naive baseline and XGBoost are scored on " + str(len(xgb_act)) + " daily values; SARIMAX is scored on " + str(len(test_monthly)) + " monthly means it forecast without seeing any of them. A single table makes them look comparable."),
    ("The baseline is undefended against trend",
     "A day-of-year mean has no trend term, and the generator injects one. Most of the gap between the baseline and everything else is that, not model quality."),
    ("No uncertainty of any kind",
     "Every prediction here is a point. The benchmark produces no intervals, no coverage and no calibration, so none is shown."),
    ("One seed, one run",
     "The tracked figures and JSON record a single reference run. The README notes that library versions may shift the numbers slightly."),
]
for label, note in LIMITS:
    w('  { label: "' + label + '", note: "' + note + '" },')
w("] as const;")
w("")

NL = chr(10)
io.open("src/content/streamflow-world.ts", "w", encoding="utf-8", newline=NL).write(NL.join(L))

# ---------------------------------------------------------------------------
# The homepage chapter's share, kept separate so the homepage does not import
# the full series for a thumbnail.
# ---------------------------------------------------------------------------

CH = []
c = CH.append
c("/*")
c(" * GENERATED by tools/gen-streamflow-world.py - do not edit by hand.")
c(" *")
c(" * The homepage chapter's share of the streamflow evidence. See streamflow-world.ts for the")
c(" * full set, and for how each number is verified against the repository's reference run.")
c(" */")
c("")
c("/** [t, actual, xgboost] over the zoomed test window, every third day. */")
c("export const chapterZoom = [")
for i in range(0, ZOOM, 3):
    t = i / (ZOOM - 1)
    c("  [" + num(t, 4) + ", " + num(float(xgb_act[i]), 2) + ", " + num(float(xgb_pred[i]), 2) + "],")
c("] as const;")
c("")
c("export const chapter = {")
c("  r2: " + num(published["XGBoost"]["R2"], 4) + ",")
c("  sarimaxR2: " + num(published["SARIMAX (Monthly)"]["R2"], 4) + ",")
c("  naiveR2: " + num(published["Seasonal Naive"]["R2"], 3) + ",")
c("  topTwoShare: " + num(top_two, 4) + ",")
c("  lag1: " + num(importances[0][1], 4) + ",")
c("  lag2: " + num(importances[1][1], 4) + ",")
c("} as const;")
c("")
io.open("src/content/streamflow-chapter.ts", "w", encoding="utf-8", newline=NL).write(NL.join(CH))

print()
print("overview %d | test %d | zoom %d | monthly %d"
      % (len(overview), len(test_idx), ZOOM, len(test_monthly)))
print("wrote src/content/streamflow-world.ts and src/content/streamflow-chapter.ts")
