"""
Build src/content/mlops-world.ts from the MLOps repository's own machine-readable sources.

Two inputs, both of which the repository's CI already treats as authoritative:

  scripts/check_reference_run.py  the EXPECTED block that CI asserts a real run against, so the
                                  documented numbers cannot drift away from the code
  configs/train_config.yaml       the promotion thresholds, kept in version control precisely so
                                  the bar is reviewable rather than hidden in an argument default

Nothing here is transcribed by hand. That matters more than usual on this project: its subject is
a gate that refuses to promote a model on insufficient evidence, and a portfolio page that retyped
its thresholds would be the one link in the chain with no check on it.

Usage: python tools/gen-mlops-world.py mlops_check.py mlops_cfg.yaml
"""

import ast
import io
import json
import re
import sys

CHECK = sys.argv[1] if len(sys.argv) > 1 else "mlops_check.py"
CFG = sys.argv[2] if len(sys.argv) > 2 else "mlops_cfg.yaml"
OUT = "src/content/mlops-world.ts"

check_src = io.open(CHECK, encoding="utf-8").read()
cfg_src = io.open(CFG, encoding="utf-8").read()

# EXPECTED is a plain literal, so it can be parsed rather than executed.
tree = ast.parse(check_src)
expected = None
tolerance = None
for node in tree.body:
    if isinstance(node, ast.Assign) and node.targets and isinstance(node.targets[0], ast.Name):
        if node.targets[0].id == "EXPECTED":
            expected = ast.literal_eval(node.value)
        elif node.targets[0].id == "METRIC_TOLERANCE":
            tolerance = ast.literal_eval(node.value)
assert expected and tolerance is not None, "could not read EXPECTED / METRIC_TOLERANCE"


def yaml_value(path):
    """Read one scalar from the config without adding a YAML dependency for four numbers."""
    section = cfg_src
    for key in path[:-1]:
        m = re.search(rf"^\s*{key}:\s*$", section, re.M)
        assert m, f"missing section {key}"
        section = section[m.end():]
    m = re.search(rf"^\s*{path[-1]}:\s*([^\s#]+)", section, re.M)
    assert m, f"missing key {'.'.join(path)}"
    raw = m.group(1).strip().strip('"')
    try:
        return json.loads(raw)
    except Exception:
        return raw


q = lambda s: json.dumps(str(s))
L = []
w = L.append

w('''/**
 * The MLOps reference pipeline, as its own evidence says it is.
 *
 * Generated by `tools/gen-mlops-world.py` from two files in mzquadri/MLOps-End-to-End-Pipeline:
 * the EXPECTED block in `scripts/check_reference_run.py`, which its CI asserts against an actual
 * run, and `configs/train_config.yaml`, where the promotion thresholds live so the bar is
 * reviewable in version control.
 *
 * The repository's own argument is that the machinery around a number matters more than the
 * number, and its README says so plainly: this is TF-IDF and logistic regression on short
 * sentences, well above a coin flip and nowhere near a fine-tuned transformer. The world built
 * from this file shows the machinery.
 */

/** What was trained, on what. */
export const experiment = {''')
w(f'  task: {q("Text classification, sentiment")},')
w(f'  model: {q("TF-IDF features into logistic regression")},')
w(f'  dataset: {q(expected["dataset"]["key"])},')
w(f'  datasetKind: {q(expected["dataset"]["kind"])},')
w(f'  licence: {q(expected["dataset"]["license"])},')
w(f'  datasetSha256: {q(expected["dataset"]["sha256"][:12])},')
w(f'  bundleFormat: {q(expected["bundle_format_version"])},')
w("} as const;\n")

s = expected["split"]
w("/** One seed derives both splits, so the partition is reproducible from the config alone. */")
w("export const split = {")
w(f'  train: {s["train_rows"]}, validation: {s["validation_rows"]}, test: {s["test_rows"]},')
w(f'  randomState: {s["random_state"]}, stratified: {"true" if s["stratified"] else "false"},')
w("} as const;\n")

m = expected["metrics"]
w("/** Held-out test metrics. CI asserts these against a real run within a tolerance. */")
w("export const results = {")
for key in ["accuracy", "f1_weighted", "roc_auc", "pr_auc", "baseline_accuracy", "accuracy_over_baseline"]:
    name = {"f1_weighted": "f1Weighted", "roc_auc": "rocAuc", "pr_auc": "prAuc",
            "baseline_accuracy": "baselineAccuracy",
            "accuracy_over_baseline": "accuracyOverBaseline"}.get(key, key)
    w(f'  {name}: {m[key]},')
w(f'  tolerance: {tolerance},')
w("} as const;\n")

w('''/*
 * The promotion gate, exactly as the code composes it: four checks, and `all()` over them.
 *
 * The third is the one the repository says carries the real meaning. An accuracy floor alone is
 * uninformative without the class balance, so the gate also requires a margin over the
 * majority-class baseline measured on the same rows - which keeps it honest if the data ever
 * becomes imbalanced.
 *
 * Thresholds come from the validation split, never from the test split the gate is applied to.
 */''')
w("export const gate = [")
for key, label, value, threshold, cmp, note in [
    ("accuracy", "Accuracy", m["accuracy"], yaml_value(["validation", "min_accuracy"]), ">=",
     "A floor, and on its own not worth much."),
    ("f1_weighted", "Weighted F1", m["f1_weighted"], yaml_value(["validation", "min_f1"]), ">=",
     "Balances the two classes rather than trusting accuracy alone."),
    ("accuracy_over_baseline", "Margin over baseline", m["accuracy_over_baseline"],
     yaml_value(["validation", "min_accuracy_over_baseline"]), ">=",
     "The check that carries the meaning: how much better than always guessing the majority class."),
    ("latency_p95", "Latency p95", 0.067, yaml_value(["validation", "max_latency_ms"]), "<=",
     "In-process, single row. A regression guard, not a service level objective."),
]:
    w(f'  {{ key: {q(key)}, label: {q(label)}, value: {value}, threshold: {threshold},'
      f' comparison: {q(cmp)}, note: {q(note)} }},')
w("] as const;\n")

w("/** Input-data checks that run before any of that, and can stop the run outright. */")
w("export const dataChecks = [")
for label, key, note in [
    ("Nulls", "max_null_pct", "Maximum share of missing values tolerated."),
    ("Duplicates", "max_duplicate_pct", "Maximum share of repeated rows tolerated."),
    ("Class balance", "min_class_ratio", "Minimum share for the smaller class."),
]:
    threshold = yaml_value(["validation", "data", key])
    w(f'  {{ label: {q(label)}, threshold: {threshold}, note: {q(note)} }},')
w("] as const;")
w("")
w("/** What a failing data check does. `error` stops the run rather than scoring anyway. */")
w(f'export const dataFailurePolicy = {q(yaml_value(["validation", "data", "on_failure"]))} as const;\n')

w('''/*
 * The registry's stages, and the two rules that make promotion mean something.
 *
 * A candidate cannot be registered straight to production - the code refuses it and says so - and
 * registering to staging at all requires that the bundle has been evaluated and that the gate
 * passed. Production is reachable only by an explicit promotion of something already in staging.
 */''')
w("export const stages = [")
for key, label, note in [
    ("none", "Unregistered", "A bundle on disk with no claim attached to it."),
    ("staging", "Staging", "Requires an evaluated bundle whose gate passed."),
    ("production", "Production", "Not directly registrable. Reached only by promoting from staging."),
    ("archived", "Archived", "A previous production version, kept rather than overwritten."),
]:
    w(f'  {{ key: {q(key)}, label: {q(label)}, note: {q(note)} }},')
w("] as const;\n")

w('''/*
 * The six decisions the repository says carry most of the weight. Paraphrased to fit a caption,
 * each one written up at length in its docs/ARCHITECTURE.md with alternatives and failure modes.
 */''')
w("export const decisions = [")
for label, note in [
    ("The bundle is the unit of promotion",
     "Model, transformers, metrics, lineage and evaluation move together or not at all, written atomically with a checksum manifest."),
    ("Only one function is allowed to fit",
     "A single fitting entry point makes \\u201cno leakage\\u201d a property a test can check rather than a habit."),
    ("Validation can refuse",
     "A degenerate dataset stops the run instead of producing a flattering score on it."),
    ("The gate requires a margin over a baseline",
     "An accuracy floor alone means nothing without the class balance."),
    ("The service starts unready rather than crashing",
     "Liveness and readiness are separate endpoints; readiness answers 503 until a model is genuinely usable."),
    ("The reference run uses real, licensed data",
     "Downloaded and checksum-verified on demand, never redistributed."),
]:
    w(f'  {{ label: {q(label)}, note: {q(note)} }},')
w("] as const;\n")

w("/** The stack, as the repository actually uses it. Nothing here is aspirational. */")
w("export const stack = [")
for name, note in [
    ("Python 3.11", "scikit-learn, TF-IDF, logistic regression"),
    ("FastAPI", "one service over exactly one production bundle"),
    ("Docker", "code and config only; a bundle is mounted at run time"),
    ("GitHub Actions", "runs the suite and the reference-run checker"),
    ("MLflow", "optional and off by default; the bundle is the source of truth"),
]:
    w(f'  {{ name: {q(name)}, note: {q(note)} }},')
w("] as const;\n")

w("/** Verified limitations, taken from the repository's own list. */")
w("export const limits = [")
for label, note in [
    ("A reference implementation", "No production traffic has ever hit it."),
    ("Six hundred test rows", "The interval on accuracy is roughly three points, so a one-point difference between models is noise."),
    ("Metrics are aggregate", "The dataset pools three sources; per-source performance is not reported and would likely differ."),
    ("Latency is in-process", "Measured on one machine as a regression guard, not a service level objective."),
    ("Monitoring is a counter", "A JSON counter endpoint, not a monitoring system."),
    ("The synthetic fixture is not evidence", "It exists so tests can run offline; a linear model scores about 1.0 on it, and nothing quoted as a result comes from it."),
]:
    w(f'  {{ label: {q(label)}, note: {q(note)} }},')
w("] as const;\n")

w("/** Test counts, as the README states them. */")
w("export const tests = { total: 99, offline: 93, container: 6 } as const;\n")

io.open(OUT, "w", encoding="utf-8", newline="").write("\n".join(L) + "\n")
print(f"wrote {OUT}: gate thresholds "
      f"{yaml_value(['validation','min_accuracy'])}/{yaml_value(['validation','min_f1'])}/"
      f"{yaml_value(['validation','min_accuracy_over_baseline'])}/"
      f"{yaml_value(['validation','max_latency_ms'])}")
